config case_sensitive = false timeframe = 30d
| preset = host_inventory_applications
| filter application_name != null and application_name != ""
| fields endpoint_name, platform, application_name, version
| alter application_name_normalized = lowercase(application_name)
| filter application_name_normalized in ("cursor", "claude code", "continue", "aider")
| alter detected_product = "UNMAPPED", product_id = "UNMAPPED", tool_family = "UNMAPPED", tool_subcategory = "UNMAPPED", expected_product_vendor = "UNMAPPED", corporate_relevance = "UNMAPPED", review_priority = "UNMAPPED"
| alter detected_product = if(application_name_normalized = "cursor", "Cursor", detected_product), product_id = if(application_name_normalized = "cursor", "cursor", product_id), tool_family = if(application_name_normalized = "cursor", "AI Development Tools", tool_family), tool_subcategory = if(application_name_normalized = "cursor", "ai-code-editor", tool_subcategory), expected_product_vendor = if(application_name_normalized = "cursor", "Anysphere", expected_product_vendor), corporate_relevance = if(application_name_normalized = "cursor", "AI-assisted engineering; review repository access, generated changes, agent privileges and data handling.", corporate_relevance), review_priority = if(application_name_normalized = "cursor", "POLICY_DEPENDENT_UNASSIGNED", review_priority)
| alter detected_product = if(application_name_normalized = "claude code", "Claude Code", detected_product), product_id = if(application_name_normalized = "claude code", "claude-code", product_id), tool_family = if(application_name_normalized = "claude code", "AI Development Tools", tool_family), tool_subcategory = if(application_name_normalized = "claude code", "coding-agent", tool_subcategory), expected_product_vendor = if(application_name_normalized = "claude code", "Anthropic", expected_product_vendor), corporate_relevance = if(application_name_normalized = "claude code", "AI-assisted engineering; review repository access, generated changes, agent privileges and data handling.", corporate_relevance), review_priority = if(application_name_normalized = "claude code", "POLICY_DEPENDENT_UNASSIGNED", review_priority)
| alter detected_product = if(application_name_normalized = "continue", "Continue", detected_product), product_id = if(application_name_normalized = "continue", "continue", product_id), tool_family = if(application_name_normalized = "continue", "AI Development Tools", tool_family), tool_subcategory = if(application_name_normalized = "continue", "coding-assistant", tool_subcategory), expected_product_vendor = if(application_name_normalized = "continue", "Continue Dev (historical); acquired by Cursor", expected_product_vendor), corporate_relevance = if(application_name_normalized = "continue", "AI-assisted engineering; review repository access, generated changes, agent privileges and data handling.", corporate_relevance), review_priority = if(application_name_normalized = "continue", "POLICY_DEPENDENT_UNASSIGNED", review_priority)
| alter detected_product = if(application_name_normalized = "aider", "Aider", detected_product), product_id = if(application_name_normalized = "aider", "aider", product_id), tool_family = if(application_name_normalized = "aider", "AI Development Tools", tool_family), tool_subcategory = if(application_name_normalized = "aider", "coding-agent", tool_subcategory), expected_product_vendor = if(application_name_normalized = "aider", "Aider project", expected_product_vendor), corporate_relevance = if(application_name_normalized = "aider", "AI-assisted engineering; review repository access, generated changes, agent privileges and data handling.", corporate_relevance), review_priority = if(application_name_normalized = "aider", "POLICY_DEPENDENT_UNASSIGNED", review_priority)
| filter product_id != "UNMAPPED"
| fields endpoint_name, platform, application_name, version, application_name_normalized, detected_product, product_id, tool_family, tool_subcategory, expected_product_vendor, corporate_relevance, review_priority
| limit 1000
