config case_sensitive = false timeframe = 30d
| preset = host_inventory_applications
| filter application_name != null and application_name != ""
| fields endpoint_name, platform, application_name, version
| alter application_name_normalized = lowercase(application_name)
| filter application_name_normalized in ("winscp", "filezilla", "filezilla client", "cyberduck", "rclone")
| alter detected_product = "UNMAPPED", product_id = "UNMAPPED", tool_family = "UNMAPPED", tool_subcategory = "UNMAPPED", expected_product_vendor = "UNMAPPED", corporate_relevance = "UNMAPPED", review_priority = "UNMAPPED"
| alter detected_product = if(application_name_normalized = "winscp", "WinSCP", detected_product), product_id = if(application_name_normalized = "winscp", "winscp", product_id), tool_family = if(application_name_normalized = "winscp", "File Transfer Tools", tool_family), tool_subcategory = if(application_name_normalized = "winscp", "secure-file-transfer", tool_subcategory), expected_product_vendor = if(application_name_normalized = "winscp", "WinSCP project", expected_product_vendor), corporate_relevance = if(application_name_normalized = "winscp", "File movement; review destinations, credentials, encryption configuration and permitted data.", corporate_relevance), review_priority = if(application_name_normalized = "winscp", "POLICY_DEPENDENT_UNASSIGNED", review_priority)
| alter detected_product = if(application_name_normalized in ("filezilla", "filezilla client"), "FileZilla Client", detected_product), product_id = if(application_name_normalized in ("filezilla", "filezilla client"), "filezilla-client", product_id), tool_family = if(application_name_normalized in ("filezilla", "filezilla client"), "File Transfer Tools", tool_family), tool_subcategory = if(application_name_normalized in ("filezilla", "filezilla client"), "file-transfer-client", tool_subcategory), expected_product_vendor = if(application_name_normalized in ("filezilla", "filezilla client"), "FileZilla project", expected_product_vendor), corporate_relevance = if(application_name_normalized in ("filezilla", "filezilla client"), "File movement; review destinations, credentials, encryption configuration and permitted data.", corporate_relevance), review_priority = if(application_name_normalized in ("filezilla", "filezilla client"), "POLICY_DEPENDENT_UNASSIGNED", review_priority)
| alter detected_product = if(application_name_normalized = "cyberduck", "Cyberduck", detected_product), product_id = if(application_name_normalized = "cyberduck", "cyberduck", product_id), tool_family = if(application_name_normalized = "cyberduck", "File Transfer Tools", tool_family), tool_subcategory = if(application_name_normalized = "cyberduck", "file-transfer-client", tool_subcategory), expected_product_vendor = if(application_name_normalized = "cyberduck", "iterate", expected_product_vendor), corporate_relevance = if(application_name_normalized = "cyberduck", "File movement; review destinations, credentials, encryption configuration and permitted data.", corporate_relevance), review_priority = if(application_name_normalized = "cyberduck", "POLICY_DEPENDENT_UNASSIGNED", review_priority)
| alter detected_product = if(application_name_normalized = "rclone", "rclone", detected_product), product_id = if(application_name_normalized = "rclone", "rclone", product_id), tool_family = if(application_name_normalized = "rclone", "File Transfer Tools", tool_family), tool_subcategory = if(application_name_normalized = "rclone", "file-transfer-automation", tool_subcategory), expected_product_vendor = if(application_name_normalized = "rclone", "rclone project", expected_product_vendor), corporate_relevance = if(application_name_normalized = "rclone", "File movement; review destinations, credentials, encryption configuration and permitted data.", corporate_relevance), review_priority = if(application_name_normalized = "rclone", "POLICY_DEPENDENT_UNASSIGNED", review_priority)
| filter product_id != "UNMAPPED"
| fields endpoint_name, platform, application_name, version, application_name_normalized, detected_product, product_id, tool_family, tool_subcategory, expected_product_vendor, corporate_relevance, review_priority
| limit 1000
