config case_sensitive = false timeframe = 30d
| preset = host_inventory_applications
| filter application_name != null and application_name != ""
| fields endpoint_name, platform, application_name, version
| alter application_name_normalized = lowercase(application_name)
| filter application_name_normalized in ("reddit", "tiktok", "instagram", "facebook")
| alter detected_product = "UNMAPPED", product_id = "UNMAPPED", tool_family = "UNMAPPED", tool_subcategory = "UNMAPPED", expected_product_vendor = "UNMAPPED", corporate_relevance = "UNMAPPED", review_priority = "UNMAPPED"
| alter detected_product = if(application_name_normalized = "reddit", "Reddit", detected_product), product_id = if(application_name_normalized = "reddit", "reddit", product_id), tool_family = if(application_name_normalized = "reddit", "Social Applications", tool_family), tool_subcategory = if(application_name_normalized = "reddit", "social-community", tool_subcategory), expected_product_vendor = if(application_name_normalized = "reddit", "Reddit", expected_product_vendor), corporate_relevance = if(application_name_normalized = "reddit", "Social publishing and community access; review account ownership, external sharing and business purpose.", corporate_relevance), review_priority = if(application_name_normalized = "reddit", "POLICY_DEPENDENT_UNASSIGNED", review_priority)
| alter detected_product = if(application_name_normalized = "tiktok", "TikTok", detected_product), product_id = if(application_name_normalized = "tiktok", "tiktok", product_id), tool_family = if(application_name_normalized = "tiktok", "Social Applications", tool_family), tool_subcategory = if(application_name_normalized = "tiktok", "social-video", tool_subcategory), expected_product_vendor = if(application_name_normalized = "tiktok", "TikTok", expected_product_vendor), corporate_relevance = if(application_name_normalized = "tiktok", "Social publishing and community access; review account ownership, external sharing and business purpose.", corporate_relevance), review_priority = if(application_name_normalized = "tiktok", "POLICY_DEPENDENT_UNASSIGNED", review_priority)
| alter detected_product = if(application_name_normalized = "instagram", "Instagram", detected_product), product_id = if(application_name_normalized = "instagram", "instagram", product_id), tool_family = if(application_name_normalized = "instagram", "Social Applications", tool_family), tool_subcategory = if(application_name_normalized = "instagram", "social-media", tool_subcategory), expected_product_vendor = if(application_name_normalized = "instagram", "Meta", expected_product_vendor), corporate_relevance = if(application_name_normalized = "instagram", "Social publishing and community access; review account ownership, external sharing and business purpose.", corporate_relevance), review_priority = if(application_name_normalized = "instagram", "POLICY_DEPENDENT_UNASSIGNED", review_priority)
| alter detected_product = if(application_name_normalized = "facebook", "Facebook", detected_product), product_id = if(application_name_normalized = "facebook", "facebook", product_id), tool_family = if(application_name_normalized = "facebook", "Social Applications", tool_family), tool_subcategory = if(application_name_normalized = "facebook", "social-media", tool_subcategory), expected_product_vendor = if(application_name_normalized = "facebook", "Meta", expected_product_vendor), corporate_relevance = if(application_name_normalized = "facebook", "Social publishing and community access; review account ownership, external sharing and business purpose.", corporate_relevance), review_priority = if(application_name_normalized = "facebook", "POLICY_DEPENDENT_UNASSIGNED", review_priority)
| filter product_id != "UNMAPPED"
| fields endpoint_name, platform, application_name, version, application_name_normalized, detected_product, product_id, tool_family, tool_subcategory, expected_product_vendor, corporate_relevance, review_priority
| limit 1000
