config case_sensitive = false timeframe = 30d
| preset = host_inventory_applications
| filter application_name != null and application_name != ""
| fields endpoint_name, platform, application_name, version
| alter application_name_normalized = lowercase(application_name)
| filter application_name_normalized in ("wireshark", "angry ip scanner", "iperf3", "fiddler everywhere")
| alter detected_product = "UNMAPPED", product_id = "UNMAPPED", tool_family = "UNMAPPED", tool_subcategory = "UNMAPPED", expected_product_vendor = "UNMAPPED", corporate_relevance = "UNMAPPED", review_priority = "UNMAPPED"
| alter detected_product = if(application_name_normalized = "wireshark", "Wireshark", detected_product), product_id = if(application_name_normalized = "wireshark", "wireshark", product_id), tool_family = if(application_name_normalized = "wireshark", "Network Utilities", tool_family), tool_subcategory = if(application_name_normalized = "wireshark", "packet-analysis", tool_subcategory), expected_product_vendor = if(application_name_normalized = "wireshark", "Wireshark Foundation", expected_product_vendor), corporate_relevance = if(application_name_normalized = "wireshark", "Network diagnostics; review authorized capture/scan scope and handling of collected traffic.", corporate_relevance), review_priority = if(application_name_normalized = "wireshark", "POLICY_DEPENDENT_UNASSIGNED", review_priority)
| alter detected_product = if(application_name_normalized = "angry ip scanner", "Angry IP Scanner", detected_product), product_id = if(application_name_normalized = "angry ip scanner", "angry-ip-scanner", product_id), tool_family = if(application_name_normalized = "angry ip scanner", "Network Utilities", tool_family), tool_subcategory = if(application_name_normalized = "angry ip scanner", "network-discovery", tool_subcategory), expected_product_vendor = if(application_name_normalized = "angry ip scanner", "Angry IP Scanner contributors", expected_product_vendor), corporate_relevance = if(application_name_normalized = "angry ip scanner", "Network diagnostics; review authorized capture/scan scope and handling of collected traffic.", corporate_relevance), review_priority = if(application_name_normalized = "angry ip scanner", "POLICY_DEPENDENT_UNASSIGNED", review_priority)
| alter detected_product = if(application_name_normalized = "iperf3", "iperf3", detected_product), product_id = if(application_name_normalized = "iperf3", "iperf3", product_id), tool_family = if(application_name_normalized = "iperf3", "Network Utilities", tool_family), tool_subcategory = if(application_name_normalized = "iperf3", "network-performance", tool_subcategory), expected_product_vendor = if(application_name_normalized = "iperf3", "ESnet", expected_product_vendor), corporate_relevance = if(application_name_normalized = "iperf3", "Network diagnostics; review authorized capture/scan scope and handling of collected traffic.", corporate_relevance), review_priority = if(application_name_normalized = "iperf3", "POLICY_DEPENDENT_UNASSIGNED", review_priority)
| alter detected_product = if(application_name_normalized = "fiddler everywhere", "Fiddler Everywhere", detected_product), product_id = if(application_name_normalized = "fiddler everywhere", "fiddler-everywhere", product_id), tool_family = if(application_name_normalized = "fiddler everywhere", "Network Utilities", tool_family), tool_subcategory = if(application_name_normalized = "fiddler everywhere", "http-diagnostics", tool_subcategory), expected_product_vendor = if(application_name_normalized = "fiddler everywhere", "Progress Software / Telerik", expected_product_vendor), corporate_relevance = if(application_name_normalized = "fiddler everywhere", "Network diagnostics; review authorized capture/scan scope and handling of collected traffic.", corporate_relevance), review_priority = if(application_name_normalized = "fiddler everywhere", "POLICY_DEPENDENT_UNASSIGNED", review_priority)
| filter product_id != "UNMAPPED"
| fields endpoint_name, platform, application_name, version, application_name_normalized, detected_product, product_id, tool_family, tool_subcategory, expected_product_vendor, corporate_relevance, review_priority
| limit 1000
