config case_sensitive = false timeframe = 30d
| preset = host_inventory_applications
| filter application_name != null and application_name != ""
| fields endpoint_name, platform, application_name, version
| alter application_name_normalized = lowercase(application_name)
| filter application_name_normalized in ("google chrome", "microsoft edge", "mozilla firefox", "firefox", "brave", "brave browser")
| alter detected_product = "UNMAPPED", product_id = "UNMAPPED", tool_family = "UNMAPPED", tool_subcategory = "UNMAPPED", expected_product_vendor = "UNMAPPED", corporate_relevance = "UNMAPPED", review_priority = "UNMAPPED"
| alter detected_product = if(application_name_normalized = "google chrome", "Google Chrome", detected_product), product_id = if(application_name_normalized = "google chrome", "google-chrome", product_id), tool_family = if(application_name_normalized = "google chrome", "Browsers", tool_family), tool_subcategory = if(application_name_normalized = "google chrome", "web-browser", tool_subcategory), expected_product_vendor = if(application_name_normalized = "google chrome", "Google", expected_product_vendor), corporate_relevance = if(application_name_normalized = "google chrome", "Web access; review update ownership, extensions, profile management and enterprise configuration.", corporate_relevance), review_priority = if(application_name_normalized = "google chrome", "POLICY_DEPENDENT_UNASSIGNED", review_priority)
| alter detected_product = if(application_name_normalized = "microsoft edge", "Microsoft Edge", detected_product), product_id = if(application_name_normalized = "microsoft edge", "microsoft-edge", product_id), tool_family = if(application_name_normalized = "microsoft edge", "Browsers", tool_family), tool_subcategory = if(application_name_normalized = "microsoft edge", "web-browser", tool_subcategory), expected_product_vendor = if(application_name_normalized = "microsoft edge", "Microsoft", expected_product_vendor), corporate_relevance = if(application_name_normalized = "microsoft edge", "Web access; review update ownership, extensions, profile management and enterprise configuration.", corporate_relevance), review_priority = if(application_name_normalized = "microsoft edge", "POLICY_DEPENDENT_UNASSIGNED", review_priority)
| alter detected_product = if(application_name_normalized in ("mozilla firefox", "firefox"), "Mozilla Firefox", detected_product), product_id = if(application_name_normalized in ("mozilla firefox", "firefox"), "mozilla-firefox", product_id), tool_family = if(application_name_normalized in ("mozilla firefox", "firefox"), "Browsers", tool_family), tool_subcategory = if(application_name_normalized in ("mozilla firefox", "firefox"), "web-browser", tool_subcategory), expected_product_vendor = if(application_name_normalized in ("mozilla firefox", "firefox"), "Mozilla", expected_product_vendor), corporate_relevance = if(application_name_normalized in ("mozilla firefox", "firefox"), "Web access; review update ownership, extensions, profile management and enterprise configuration.", corporate_relevance), review_priority = if(application_name_normalized in ("mozilla firefox", "firefox"), "POLICY_DEPENDENT_UNASSIGNED", review_priority)
| alter detected_product = if(application_name_normalized in ("brave", "brave browser"), "Brave Browser", detected_product), product_id = if(application_name_normalized in ("brave", "brave browser"), "brave-browser", product_id), tool_family = if(application_name_normalized in ("brave", "brave browser"), "Browsers", tool_family), tool_subcategory = if(application_name_normalized in ("brave", "brave browser"), "web-browser", tool_subcategory), expected_product_vendor = if(application_name_normalized in ("brave", "brave browser"), "Brave Software", expected_product_vendor), corporate_relevance = if(application_name_normalized in ("brave", "brave browser"), "Web access; review update ownership, extensions, profile management and enterprise configuration.", corporate_relevance), review_priority = if(application_name_normalized in ("brave", "brave browser"), "POLICY_DEPENDENT_UNASSIGNED", review_priority)
| filter product_id != "UNMAPPED"
| fields endpoint_name, platform, application_name, version, application_name_normalized, detected_product, product_id, tool_family, tool_subcategory, expected_product_vendor, corporate_relevance, review_priority
| limit 1000
