config case_sensitive = false timeframe = 30d
| preset = host_inventory_applications
| filter application_name != null and application_name != ""
| fields endpoint_name, platform, application_name, version
| alter application_name_normalized = lowercase(application_name)
| filter application_name_normalized in ("git for windows", "git", "postman", "insomnia", "github desktop")
| alter detected_product = "UNMAPPED", product_id = "UNMAPPED", tool_family = "UNMAPPED", tool_subcategory = "UNMAPPED", expected_product_vendor = "UNMAPPED", corporate_relevance = "UNMAPPED", review_priority = "UNMAPPED"
| alter detected_product = if(application_name_normalized in ("git for windows", "git"), "Git for Windows", detected_product), product_id = if(application_name_normalized in ("git for windows", "git"), "git-for-windows", product_id), tool_family = if(application_name_normalized in ("git for windows", "git"), "Developer Utilities", tool_family), tool_subcategory = if(application_name_normalized in ("git for windows", "git"), "version-control", tool_subcategory), expected_product_vendor = if(application_name_normalized in ("git for windows", "git"), "Git for Windows contributors", expected_product_vendor), corporate_relevance = if(application_name_normalized in ("git for windows", "git"), "Engineering support; review package provenance, credentials, API targets and update ownership.", corporate_relevance), review_priority = if(application_name_normalized in ("git for windows", "git"), "POLICY_DEPENDENT_UNASSIGNED", review_priority)
| alter detected_product = if(application_name_normalized = "postman", "Postman", detected_product), product_id = if(application_name_normalized = "postman", "postman", product_id), tool_family = if(application_name_normalized = "postman", "Developer Utilities", tool_family), tool_subcategory = if(application_name_normalized = "postman", "api-client", tool_subcategory), expected_product_vendor = if(application_name_normalized = "postman", "Postman", expected_product_vendor), corporate_relevance = if(application_name_normalized = "postman", "Engineering support; review package provenance, credentials, API targets and update ownership.", corporate_relevance), review_priority = if(application_name_normalized = "postman", "POLICY_DEPENDENT_UNASSIGNED", review_priority)
| alter detected_product = if(application_name_normalized = "insomnia", "Insomnia", detected_product), product_id = if(application_name_normalized = "insomnia", "insomnia", product_id), tool_family = if(application_name_normalized = "insomnia", "Developer Utilities", tool_family), tool_subcategory = if(application_name_normalized = "insomnia", "api-client", tool_subcategory), expected_product_vendor = if(application_name_normalized = "insomnia", "Kong", expected_product_vendor), corporate_relevance = if(application_name_normalized = "insomnia", "Engineering support; review package provenance, credentials, API targets and update ownership.", corporate_relevance), review_priority = if(application_name_normalized = "insomnia", "POLICY_DEPENDENT_UNASSIGNED", review_priority)
| alter detected_product = if(application_name_normalized = "github desktop", "GitHub Desktop", detected_product), product_id = if(application_name_normalized = "github desktop", "github-desktop", product_id), tool_family = if(application_name_normalized = "github desktop", "Developer Utilities", tool_family), tool_subcategory = if(application_name_normalized = "github desktop", "version-control-client", tool_subcategory), expected_product_vendor = if(application_name_normalized = "github desktop", "GitHub / Microsoft", expected_product_vendor), corporate_relevance = if(application_name_normalized = "github desktop", "Engineering support; review package provenance, credentials, API targets and update ownership.", corporate_relevance), review_priority = if(application_name_normalized = "github desktop", "POLICY_DEPENDENT_UNASSIGNED", review_priority)
| filter product_id != "UNMAPPED"
| fields endpoint_name, platform, application_name, version, application_name_normalized, detected_product, product_id, tool_family, tool_subcategory, expected_product_vendor, corporate_relevance, review_priority
| limit 1000
