config case_sensitive = false timeframe = 30d
| preset = host_inventory_applications
| filter application_name != null and application_name != ""
| fields endpoint_name, platform, application_name, version
| alter application_name_normalized = lowercase(application_name)
| filter application_name_normalized in ("nmap", "burp suite community edition", "burp suite professional", "metasploit framework", "bloodhound community edition")
| alter detected_product = "UNMAPPED", product_id = "UNMAPPED", tool_family = "UNMAPPED", tool_subcategory = "UNMAPPED", expected_product_vendor = "UNMAPPED", corporate_relevance = "UNMAPPED", review_priority = "UNMAPPED"
| alter detected_product = if(application_name_normalized = "nmap", "Nmap", detected_product), product_id = if(application_name_normalized = "nmap", "nmap", product_id), tool_family = if(application_name_normalized = "nmap", "Penetration Testing / Dual-Use Security Tools", tool_family), tool_subcategory = if(application_name_normalized = "nmap", "network-assessment", tool_subcategory), expected_product_vendor = if(application_name_normalized = "nmap", "Nmap Project", expected_product_vendor), corporate_relevance = if(application_name_normalized = "nmap", "Authorized assessment tooling; review engagement scope, credential handling and permitted operators.", corporate_relevance), review_priority = if(application_name_normalized = "nmap", "POLICY_DEPENDENT_UNASSIGNED", review_priority)
| alter detected_product = if(application_name_normalized in ("burp suite community edition", "burp suite professional"), "Burp Suite", detected_product), product_id = if(application_name_normalized in ("burp suite community edition", "burp suite professional"), "burp-suite", product_id), tool_family = if(application_name_normalized in ("burp suite community edition", "burp suite professional"), "Penetration Testing / Dual-Use Security Tools", tool_family), tool_subcategory = if(application_name_normalized in ("burp suite community edition", "burp suite professional"), "web-assessment", tool_subcategory), expected_product_vendor = if(application_name_normalized in ("burp suite community edition", "burp suite professional"), "PortSwigger", expected_product_vendor), corporate_relevance = if(application_name_normalized in ("burp suite community edition", "burp suite professional"), "Authorized assessment tooling; review engagement scope, credential handling and permitted operators.", corporate_relevance), review_priority = if(application_name_normalized in ("burp suite community edition", "burp suite professional"), "POLICY_DEPENDENT_UNASSIGNED", review_priority)
| alter detected_product = if(application_name_normalized = "metasploit framework", "Metasploit Framework", detected_product), product_id = if(application_name_normalized = "metasploit framework", "metasploit-framework", product_id), tool_family = if(application_name_normalized = "metasploit framework", "Penetration Testing / Dual-Use Security Tools", tool_family), tool_subcategory = if(application_name_normalized = "metasploit framework", "assessment-framework", tool_subcategory), expected_product_vendor = if(application_name_normalized = "metasploit framework", "Rapid7 / Metasploit contributors", expected_product_vendor), corporate_relevance = if(application_name_normalized = "metasploit framework", "Authorized assessment tooling; review engagement scope, credential handling and permitted operators.", corporate_relevance), review_priority = if(application_name_normalized = "metasploit framework", "POLICY_DEPENDENT_UNASSIGNED", review_priority)
| alter detected_product = if(application_name_normalized = "bloodhound community edition", "BloodHound Community Edition", detected_product), product_id = if(application_name_normalized = "bloodhound community edition", "bloodhound-community", product_id), tool_family = if(application_name_normalized = "bloodhound community edition", "Penetration Testing / Dual-Use Security Tools", tool_family), tool_subcategory = if(application_name_normalized = "bloodhound community edition", "identity-assessment", tool_subcategory), expected_product_vendor = if(application_name_normalized = "bloodhound community edition", "SpecterOps", expected_product_vendor), corporate_relevance = if(application_name_normalized = "bloodhound community edition", "Authorized assessment tooling; review engagement scope, credential handling and permitted operators.", corporate_relevance), review_priority = if(application_name_normalized = "bloodhound community edition", "POLICY_DEPENDENT_UNASSIGNED", review_priority)
| filter product_id != "UNMAPPED"
| fields endpoint_name, platform, application_name, version, application_name_normalized, detected_product, product_id, tool_family, tool_subcategory, expected_product_vendor, corporate_relevance, review_priority
| limit 1000
