config case_sensitive = false timeframe = 30d
| preset = host_inventory_applications
| filter application_name != null and application_name != ""
| fields endpoint_name, platform, application_name, version
| alter application_name_normalized = lowercase(application_name)
| filter application_name_normalized in ("cortex xdr", "cortex xdr agent", "crowdstrike falcon sensor", "sentinelone agent", "microsoft defender for endpoint")
| alter detected_product = "UNMAPPED", product_id = "UNMAPPED", tool_family = "UNMAPPED", tool_subcategory = "UNMAPPED", expected_product_vendor = "UNMAPPED", corporate_relevance = "UNMAPPED", review_priority = "UNMAPPED"
| alter detected_product = if(application_name_normalized in ("cortex xdr", "cortex xdr agent"), "Cortex XDR Agent", detected_product), product_id = if(application_name_normalized in ("cortex xdr", "cortex xdr agent"), "cortex-xdr-agent", product_id), tool_family = if(application_name_normalized in ("cortex xdr", "cortex xdr agent"), "EDR / Endpoint Security", tool_family), tool_subcategory = if(application_name_normalized in ("cortex xdr", "cortex xdr agent"), "endpoint-agent", tool_subcategory), expected_product_vendor = if(application_name_normalized in ("cortex xdr", "cortex xdr agent"), "Palo Alto Networks", expected_product_vendor), corporate_relevance = if(application_name_normalized in ("cortex xdr", "cortex xdr agent"), "Endpoint protection and response; installation does not establish sensor health, enrollment or coverage.", corporate_relevance), review_priority = if(application_name_normalized in ("cortex xdr", "cortex xdr agent"), "POLICY_DEPENDENT_UNASSIGNED", review_priority)
| alter detected_product = if(application_name_normalized = "crowdstrike falcon sensor", "CrowdStrike Falcon Sensor", detected_product), product_id = if(application_name_normalized = "crowdstrike falcon sensor", "crowdstrike-falcon-sensor", product_id), tool_family = if(application_name_normalized = "crowdstrike falcon sensor", "EDR / Endpoint Security", tool_family), tool_subcategory = if(application_name_normalized = "crowdstrike falcon sensor", "endpoint-agent", tool_subcategory), expected_product_vendor = if(application_name_normalized = "crowdstrike falcon sensor", "CrowdStrike", expected_product_vendor), corporate_relevance = if(application_name_normalized = "crowdstrike falcon sensor", "Endpoint protection and response; installation does not establish sensor health, enrollment or coverage.", corporate_relevance), review_priority = if(application_name_normalized = "crowdstrike falcon sensor", "POLICY_DEPENDENT_UNASSIGNED", review_priority)
| alter detected_product = if(application_name_normalized = "sentinelone agent", "SentinelOne Agent", detected_product), product_id = if(application_name_normalized = "sentinelone agent", "sentinelone-agent", product_id), tool_family = if(application_name_normalized = "sentinelone agent", "EDR / Endpoint Security", tool_family), tool_subcategory = if(application_name_normalized = "sentinelone agent", "endpoint-agent", tool_subcategory), expected_product_vendor = if(application_name_normalized = "sentinelone agent", "SentinelOne", expected_product_vendor), corporate_relevance = if(application_name_normalized = "sentinelone agent", "Endpoint protection and response; installation does not establish sensor health, enrollment or coverage.", corporate_relevance), review_priority = if(application_name_normalized = "sentinelone agent", "POLICY_DEPENDENT_UNASSIGNED", review_priority)
| alter detected_product = if(application_name_normalized = "microsoft defender for endpoint", "Microsoft Defender for Endpoint", detected_product), product_id = if(application_name_normalized = "microsoft defender for endpoint", "microsoft-defender-endpoint", product_id), tool_family = if(application_name_normalized = "microsoft defender for endpoint", "EDR / Endpoint Security", tool_family), tool_subcategory = if(application_name_normalized = "microsoft defender for endpoint", "endpoint-security", tool_subcategory), expected_product_vendor = if(application_name_normalized = "microsoft defender for endpoint", "Microsoft", expected_product_vendor), corporate_relevance = if(application_name_normalized = "microsoft defender for endpoint", "Endpoint protection and response; installation does not establish sensor health, enrollment or coverage.", corporate_relevance), review_priority = if(application_name_normalized = "microsoft defender for endpoint", "POLICY_DEPENDENT_UNASSIGNED", review_priority)
| filter product_id != "UNMAPPED"
| fields endpoint_name, platform, application_name, version, application_name_normalized, detected_product, product_id, tool_family, tool_subcategory, expected_product_vendor, corporate_relevance, review_priority
| limit 1000
