config case_sensitive = false timeframe = 30d
| preset = host_inventory_applications
| filter application_name != null and application_name != ""
| fields endpoint_name, platform, application_name, version
| alter application_name_normalized = lowercase(application_name)
| filter application_name_normalized in ("putty", "openssh", "openssh client", "openssh server", "mobaxterm", "mobaxterm personal edition", "mobaxterm professional edition", "termius")
| alter detected_product = "UNMAPPED", product_id = "UNMAPPED", tool_family = "UNMAPPED", tool_subcategory = "UNMAPPED", expected_product_vendor = "UNMAPPED", corporate_relevance = "UNMAPPED", review_priority = "UNMAPPED"
| alter detected_product = if(application_name_normalized = "putty", "PuTTY", detected_product), product_id = if(application_name_normalized = "putty", "putty", product_id), tool_family = if(application_name_normalized = "putty", "Remote Shell / SSH Tools", tool_family), tool_subcategory = if(application_name_normalized = "putty", "ssh-client", tool_subcategory), expected_product_vendor = if(application_name_normalized = "putty", "Simon Tatham / PuTTY contributors", expected_product_vendor), corporate_relevance = if(application_name_normalized = "putty", "Remote command access; review keys, server trust, session destinations and forwarding configuration.", corporate_relevance), review_priority = if(application_name_normalized = "putty", "POLICY_DEPENDENT_UNASSIGNED", review_priority)
| alter detected_product = if(application_name_normalized in ("openssh", "openssh client", "openssh server"), "OpenSSH", detected_product), product_id = if(application_name_normalized in ("openssh", "openssh client", "openssh server"), "openssh", product_id), tool_family = if(application_name_normalized in ("openssh", "openssh client", "openssh server"), "Remote Shell / SSH Tools", tool_family), tool_subcategory = if(application_name_normalized in ("openssh", "openssh client", "openssh server"), "ssh-suite", tool_subcategory), expected_product_vendor = if(application_name_normalized in ("openssh", "openssh client", "openssh server"), "OpenBSD / OpenSSH contributors", expected_product_vendor), corporate_relevance = if(application_name_normalized in ("openssh", "openssh client", "openssh server"), "Remote command access; review keys, server trust, session destinations and forwarding configuration.", corporate_relevance), review_priority = if(application_name_normalized in ("openssh", "openssh client", "openssh server"), "POLICY_DEPENDENT_UNASSIGNED", review_priority)
| alter detected_product = if(application_name_normalized in ("mobaxterm", "mobaxterm personal edition", "mobaxterm professional edition"), "MobaXterm", detected_product), product_id = if(application_name_normalized in ("mobaxterm", "mobaxterm personal edition", "mobaxterm professional edition"), "mobaxterm", product_id), tool_family = if(application_name_normalized in ("mobaxterm", "mobaxterm personal edition", "mobaxterm professional edition"), "Remote Shell / SSH Tools", tool_family), tool_subcategory = if(application_name_normalized in ("mobaxterm", "mobaxterm personal edition", "mobaxterm professional edition"), "remote-terminal", tool_subcategory), expected_product_vendor = if(application_name_normalized in ("mobaxterm", "mobaxterm personal edition", "mobaxterm professional edition"), "Mobatek", expected_product_vendor), corporate_relevance = if(application_name_normalized in ("mobaxterm", "mobaxterm personal edition", "mobaxterm professional edition"), "Remote command access; review keys, server trust, session destinations and forwarding configuration.", corporate_relevance), review_priority = if(application_name_normalized in ("mobaxterm", "mobaxterm personal edition", "mobaxterm professional edition"), "POLICY_DEPENDENT_UNASSIGNED", review_priority)
| alter detected_product = if(application_name_normalized = "termius", "Termius", detected_product), product_id = if(application_name_normalized = "termius", "termius", product_id), tool_family = if(application_name_normalized = "termius", "Remote Shell / SSH Tools", tool_family), tool_subcategory = if(application_name_normalized = "termius", "ssh-client", tool_subcategory), expected_product_vendor = if(application_name_normalized = "termius", "Termius", expected_product_vendor), corporate_relevance = if(application_name_normalized = "termius", "Remote command access; review keys, server trust, session destinations and forwarding configuration.", corporate_relevance), review_priority = if(application_name_normalized = "termius", "POLICY_DEPENDENT_UNASSIGNED", review_priority)
| filter product_id != "UNMAPPED"
| fields endpoint_name, platform, application_name, version, application_name_normalized, detected_product, product_id, tool_family, tool_subcategory, expected_product_vendor, corporate_relevance, review_priority
| limit 1000
