config case_sensitive = false timeframe = 30d
| preset = host_inventory_applications
| filter application_name != null and application_name != ""
| fields endpoint_name, platform, application_name, version
| alter application_name_normalized = lowercase(application_name)
| filter application_name_normalized in ("qbittorrent", "transmission", "deluge", "bittorrent classic")
| alter detected_product = "UNMAPPED", product_id = "UNMAPPED", tool_family = "UNMAPPED", tool_subcategory = "UNMAPPED", expected_product_vendor = "UNMAPPED", corporate_relevance = "UNMAPPED", review_priority = "UNMAPPED"
| alter detected_product = if(application_name_normalized = "qbittorrent", "qBittorrent", detected_product), product_id = if(application_name_normalized = "qbittorrent", "qbittorrent", product_id), tool_family = if(application_name_normalized = "qbittorrent", "P2P / Torrent", tool_family), tool_subcategory = if(application_name_normalized = "qbittorrent", "bittorrent-client", tool_subcategory), expected_product_vendor = if(application_name_normalized = "qbittorrent", "qBittorrent project", expected_product_vendor), corporate_relevance = if(application_name_normalized = "qbittorrent", "Peer-to-peer distribution; review content authorization, bandwidth and listening/network policy.", corporate_relevance), review_priority = if(application_name_normalized = "qbittorrent", "POLICY_DEPENDENT_UNASSIGNED", review_priority)
| alter detected_product = if(application_name_normalized = "transmission", "Transmission", detected_product), product_id = if(application_name_normalized = "transmission", "transmission", product_id), tool_family = if(application_name_normalized = "transmission", "P2P / Torrent", tool_family), tool_subcategory = if(application_name_normalized = "transmission", "bittorrent-client", tool_subcategory), expected_product_vendor = if(application_name_normalized = "transmission", "Transmission project", expected_product_vendor), corporate_relevance = if(application_name_normalized = "transmission", "Peer-to-peer distribution; review content authorization, bandwidth and listening/network policy.", corporate_relevance), review_priority = if(application_name_normalized = "transmission", "POLICY_DEPENDENT_UNASSIGNED", review_priority)
| alter detected_product = if(application_name_normalized = "deluge", "Deluge", detected_product), product_id = if(application_name_normalized = "deluge", "deluge", product_id), tool_family = if(application_name_normalized = "deluge", "P2P / Torrent", tool_family), tool_subcategory = if(application_name_normalized = "deluge", "bittorrent-client", tool_subcategory), expected_product_vendor = if(application_name_normalized = "deluge", "Deluge Team", expected_product_vendor), corporate_relevance = if(application_name_normalized = "deluge", "Peer-to-peer distribution; review content authorization, bandwidth and listening/network policy.", corporate_relevance), review_priority = if(application_name_normalized = "deluge", "POLICY_DEPENDENT_UNASSIGNED", review_priority)
| alter detected_product = if(application_name_normalized = "bittorrent classic", "BitTorrent Classic", detected_product), product_id = if(application_name_normalized = "bittorrent classic", "bittorrent-classic", product_id), tool_family = if(application_name_normalized = "bittorrent classic", "P2P / Torrent", tool_family), tool_subcategory = if(application_name_normalized = "bittorrent classic", "bittorrent-client", tool_subcategory), expected_product_vendor = if(application_name_normalized = "bittorrent classic", "BitTorrent", expected_product_vendor), corporate_relevance = if(application_name_normalized = "bittorrent classic", "Peer-to-peer distribution; review content authorization, bandwidth and listening/network policy.", corporate_relevance), review_priority = if(application_name_normalized = "bittorrent classic", "POLICY_DEPENDENT_UNASSIGNED", review_priority)
| filter product_id != "UNMAPPED"
| fields endpoint_name, platform, application_name, version, application_name_normalized, detected_product, product_id, tool_family, tool_subcategory, expected_product_vendor, corporate_relevance, review_priority
| limit 1000
