config case_sensitive = false timeframe = 30d
| preset = host_inventory_applications
| filter application_name != null and application_name != ""
| fields endpoint_name, platform, application_name, version
| alter application_name_normalized = lowercase(application_name)
| filter application_name_normalized in ("powershell", "powershell 7", "python", "autohotkey", "node.js")
| alter detected_product = "UNMAPPED", product_id = "UNMAPPED", tool_family = "UNMAPPED", tool_subcategory = "UNMAPPED", expected_product_vendor = "UNMAPPED", corporate_relevance = "UNMAPPED", review_priority = "UNMAPPED"
| alter detected_product = if(application_name_normalized in ("powershell", "powershell 7"), "PowerShell 7", detected_product), product_id = if(application_name_normalized in ("powershell", "powershell 7"), "powershell7", product_id), tool_family = if(application_name_normalized in ("powershell", "powershell 7"), "Scripting / Automation Tools", tool_family), tool_subcategory = if(application_name_normalized in ("powershell", "powershell 7"), "shell-automation", tool_subcategory), expected_product_vendor = if(application_name_normalized in ("powershell", "powershell 7"), "Microsoft", expected_product_vendor), corporate_relevance = if(application_name_normalized in ("powershell", "powershell 7"), "Automation and interpreters; review script provenance, credentials, privileges and execution ownership.", corporate_relevance), review_priority = if(application_name_normalized in ("powershell", "powershell 7"), "POLICY_DEPENDENT_UNASSIGNED", review_priority)
| alter detected_product = if(application_name_normalized = "python", "Python", detected_product), product_id = if(application_name_normalized = "python", "python", product_id), tool_family = if(application_name_normalized = "python", "Scripting / Automation Tools", tool_family), tool_subcategory = if(application_name_normalized = "python", "language-runtime", tool_subcategory), expected_product_vendor = if(application_name_normalized = "python", "Python Software Foundation", expected_product_vendor), corporate_relevance = if(application_name_normalized = "python", "Automation and interpreters; review script provenance, credentials, privileges and execution ownership.", corporate_relevance), review_priority = if(application_name_normalized = "python", "POLICY_DEPENDENT_UNASSIGNED", review_priority)
| alter detected_product = if(application_name_normalized = "autohotkey", "AutoHotkey", detected_product), product_id = if(application_name_normalized = "autohotkey", "autohotkey", product_id), tool_family = if(application_name_normalized = "autohotkey", "Scripting / Automation Tools", tool_family), tool_subcategory = if(application_name_normalized = "autohotkey", "desktop-automation", tool_subcategory), expected_product_vendor = if(application_name_normalized = "autohotkey", "AutoHotkey Foundation / contributors", expected_product_vendor), corporate_relevance = if(application_name_normalized = "autohotkey", "Automation and interpreters; review script provenance, credentials, privileges and execution ownership.", corporate_relevance), review_priority = if(application_name_normalized = "autohotkey", "POLICY_DEPENDENT_UNASSIGNED", review_priority)
| alter detected_product = if(application_name_normalized = "node.js", "Node.js", detected_product), product_id = if(application_name_normalized = "node.js", "nodejs", product_id), tool_family = if(application_name_normalized = "node.js", "Scripting / Automation Tools", tool_family), tool_subcategory = if(application_name_normalized = "node.js", "javascript-runtime", tool_subcategory), expected_product_vendor = if(application_name_normalized = "node.js", "OpenJS Foundation / contributors", expected_product_vendor), corporate_relevance = if(application_name_normalized = "node.js", "Automation and interpreters; review script provenance, credentials, privileges and execution ownership.", corporate_relevance), review_priority = if(application_name_normalized = "node.js", "POLICY_DEPENDENT_UNASSIGNED", review_priority)
| filter product_id != "UNMAPPED"
| fields endpoint_name, platform, application_name, version, application_name_normalized, detected_product, product_id, tool_family, tool_subcategory, expected_product_vendor, corporate_relevance, review_priority
| limit 1000
