config case_sensitive = false timeframe = 30d
| preset = host_inventory_applications
| filter application_name != null and application_name != ""
| fields endpoint_name, platform, application_name, version
| alter application_name_normalized = lowercase(application_name)
| filter application_name_normalized in ("dbeaver", "dbeaver community", "heidisql", "pgadmin 4", "mysql workbench")
| alter detected_product = "UNMAPPED", product_id = "UNMAPPED", tool_family = "UNMAPPED", tool_subcategory = "UNMAPPED", expected_product_vendor = "UNMAPPED", corporate_relevance = "UNMAPPED", review_priority = "UNMAPPED"
| alter detected_product = if(application_name_normalized in ("dbeaver", "dbeaver community"), "DBeaver Community", detected_product), product_id = if(application_name_normalized in ("dbeaver", "dbeaver community"), "dbeaver-community", product_id), tool_family = if(application_name_normalized in ("dbeaver", "dbeaver community"), "Database Clients", tool_family), tool_subcategory = if(application_name_normalized in ("dbeaver", "dbeaver community"), "database-client", tool_subcategory), expected_product_vendor = if(application_name_normalized in ("dbeaver", "dbeaver community"), "DBeaver", expected_product_vendor), corporate_relevance = if(application_name_normalized in ("dbeaver", "dbeaver community"), "Database access; review connection secrets, production privileges, exports and approved destinations.", corporate_relevance), review_priority = if(application_name_normalized in ("dbeaver", "dbeaver community"), "POLICY_DEPENDENT_UNASSIGNED", review_priority)
| alter detected_product = if(application_name_normalized = "heidisql", "HeidiSQL", detected_product), product_id = if(application_name_normalized = "heidisql", "heidisql", product_id), tool_family = if(application_name_normalized = "heidisql", "Database Clients", tool_family), tool_subcategory = if(application_name_normalized = "heidisql", "database-client", tool_subcategory), expected_product_vendor = if(application_name_normalized = "heidisql", "HeidiSQL project", expected_product_vendor), corporate_relevance = if(application_name_normalized = "heidisql", "Database access; review connection secrets, production privileges, exports and approved destinations.", corporate_relevance), review_priority = if(application_name_normalized = "heidisql", "POLICY_DEPENDENT_UNASSIGNED", review_priority)
| alter detected_product = if(application_name_normalized = "pgadmin 4", "pgAdmin 4", detected_product), product_id = if(application_name_normalized = "pgadmin 4", "pgadmin4", product_id), tool_family = if(application_name_normalized = "pgadmin 4", "Database Clients", tool_family), tool_subcategory = if(application_name_normalized = "pgadmin 4", "postgresql-administration", tool_subcategory), expected_product_vendor = if(application_name_normalized = "pgadmin 4", "pgAdmin Development Team", expected_product_vendor), corporate_relevance = if(application_name_normalized = "pgadmin 4", "Database access; review connection secrets, production privileges, exports and approved destinations.", corporate_relevance), review_priority = if(application_name_normalized = "pgadmin 4", "POLICY_DEPENDENT_UNASSIGNED", review_priority)
| alter detected_product = if(application_name_normalized = "mysql workbench", "MySQL Workbench", detected_product), product_id = if(application_name_normalized = "mysql workbench", "mysql-workbench", product_id), tool_family = if(application_name_normalized = "mysql workbench", "Database Clients", tool_family), tool_subcategory = if(application_name_normalized = "mysql workbench", "database-client", tool_subcategory), expected_product_vendor = if(application_name_normalized = "mysql workbench", "Oracle", expected_product_vendor), corporate_relevance = if(application_name_normalized = "mysql workbench", "Database access; review connection secrets, production privileges, exports and approved destinations.", corporate_relevance), review_priority = if(application_name_normalized = "mysql workbench", "POLICY_DEPENDENT_UNASSIGNED", review_priority)
| filter product_id != "UNMAPPED"
| fields endpoint_name, platform, application_name, version, application_name_normalized, detected_product, product_id, tool_family, tool_subcategory, expected_product_vendor, corporate_relevance, review_priority
| limit 1000
