config case_sensitive = false timeframe = 30d
| preset = host_inventory_applications
| filter application_name != null and application_name != ""
| fields endpoint_name, platform, application_name, version
| alter application_name_normalized = lowercase(application_name)
| filter application_name_normalized in ("microsoft onedrive", "google drive", "google drive for desktop", "dropbox", "syncthing")
| alter detected_product = "UNMAPPED", product_id = "UNMAPPED", tool_family = "UNMAPPED", tool_subcategory = "UNMAPPED", expected_product_vendor = "UNMAPPED", corporate_relevance = "UNMAPPED", review_priority = "UNMAPPED"
| alter detected_product = if(application_name_normalized = "microsoft onedrive", "Microsoft OneDrive", detected_product), product_id = if(application_name_normalized = "microsoft onedrive", "onedrive", product_id), tool_family = if(application_name_normalized = "microsoft onedrive", "Cloud Storage / File Synchronization", tool_family), tool_subcategory = if(application_name_normalized = "microsoft onedrive", "cloud-file-sync", tool_subcategory), expected_product_vendor = if(application_name_normalized = "microsoft onedrive", "Microsoft", expected_product_vendor), corporate_relevance = if(application_name_normalized = "microsoft onedrive", "Data synchronization; review account tenancy, shared folders, retention and data classification.", corporate_relevance), review_priority = if(application_name_normalized = "microsoft onedrive", "POLICY_DEPENDENT_UNASSIGNED", review_priority)
| alter detected_product = if(application_name_normalized in ("google drive", "google drive for desktop"), "Google Drive for desktop", detected_product), product_id = if(application_name_normalized in ("google drive", "google drive for desktop"), "google-drive-desktop", product_id), tool_family = if(application_name_normalized in ("google drive", "google drive for desktop"), "Cloud Storage / File Synchronization", tool_family), tool_subcategory = if(application_name_normalized in ("google drive", "google drive for desktop"), "cloud-file-sync", tool_subcategory), expected_product_vendor = if(application_name_normalized in ("google drive", "google drive for desktop"), "Google", expected_product_vendor), corporate_relevance = if(application_name_normalized in ("google drive", "google drive for desktop"), "Data synchronization; review account tenancy, shared folders, retention and data classification.", corporate_relevance), review_priority = if(application_name_normalized in ("google drive", "google drive for desktop"), "POLICY_DEPENDENT_UNASSIGNED", review_priority)
| alter detected_product = if(application_name_normalized = "dropbox", "Dropbox desktop app", detected_product), product_id = if(application_name_normalized = "dropbox", "dropbox", product_id), tool_family = if(application_name_normalized = "dropbox", "Cloud Storage / File Synchronization", tool_family), tool_subcategory = if(application_name_normalized = "dropbox", "cloud-file-sync", tool_subcategory), expected_product_vendor = if(application_name_normalized = "dropbox", "Dropbox", expected_product_vendor), corporate_relevance = if(application_name_normalized = "dropbox", "Data synchronization; review account tenancy, shared folders, retention and data classification.", corporate_relevance), review_priority = if(application_name_normalized = "dropbox", "POLICY_DEPENDENT_UNASSIGNED", review_priority)
| alter detected_product = if(application_name_normalized = "syncthing", "Syncthing", detected_product), product_id = if(application_name_normalized = "syncthing", "syncthing", product_id), tool_family = if(application_name_normalized = "syncthing", "Cloud Storage / File Synchronization", tool_family), tool_subcategory = if(application_name_normalized = "syncthing", "peer-file-sync", tool_subcategory), expected_product_vendor = if(application_name_normalized = "syncthing", "Syncthing Foundation / contributors", expected_product_vendor), corporate_relevance = if(application_name_normalized = "syncthing", "Data synchronization; review account tenancy, shared folders, retention and data classification.", corporate_relevance), review_priority = if(application_name_normalized = "syncthing", "POLICY_DEPENDENT_UNASSIGNED", review_priority)
| filter product_id != "UNMAPPED"
| fields endpoint_name, platform, application_name, version, application_name_normalized, detected_product, product_id, tool_family, tool_subcategory, expected_product_vendor, corporate_relevance, review_priority
| limit 1000
