config case_sensitive = false timeframe = 30d
| preset = host_inventory_applications
| filter application_name != null and application_name != ""
| fields endpoint_name, platform, application_name, version
| alter application_name_normalized = lowercase(application_name)
| filter application_name_normalized in ("oracle virtualbox", "oracle vm virtualbox", "vmware workstation", "vmware workstation pro", "parallels desktop", "qemu")
| alter detected_product = "UNMAPPED", product_id = "UNMAPPED", tool_family = "UNMAPPED", tool_subcategory = "UNMAPPED", expected_product_vendor = "UNMAPPED", corporate_relevance = "UNMAPPED", review_priority = "UNMAPPED"
| alter detected_product = if(application_name_normalized in ("oracle virtualbox", "oracle vm virtualbox"), "Oracle VirtualBox", detected_product), product_id = if(application_name_normalized in ("oracle virtualbox", "oracle vm virtualbox"), "virtualbox", product_id), tool_family = if(application_name_normalized in ("oracle virtualbox", "oracle vm virtualbox"), "Virtualization", tool_family), tool_subcategory = if(application_name_normalized in ("oracle virtualbox", "oracle vm virtualbox"), "desktop-hypervisor", tool_subcategory), expected_product_vendor = if(application_name_normalized in ("oracle virtualbox", "oracle vm virtualbox"), "Oracle", expected_product_vendor), corporate_relevance = if(application_name_normalized in ("oracle virtualbox", "oracle vm virtualbox"), "Guest environments; review guest patching, virtual networking, images and asset visibility.", corporate_relevance), review_priority = if(application_name_normalized in ("oracle virtualbox", "oracle vm virtualbox"), "POLICY_DEPENDENT_UNASSIGNED", review_priority)
| alter detected_product = if(application_name_normalized in ("vmware workstation", "vmware workstation pro"), "VMware Workstation Pro", detected_product), product_id = if(application_name_normalized in ("vmware workstation", "vmware workstation pro"), "vmware-workstation", product_id), tool_family = if(application_name_normalized in ("vmware workstation", "vmware workstation pro"), "Virtualization", tool_family), tool_subcategory = if(application_name_normalized in ("vmware workstation", "vmware workstation pro"), "desktop-hypervisor", tool_subcategory), expected_product_vendor = if(application_name_normalized in ("vmware workstation", "vmware workstation pro"), "Broadcom / VMware", expected_product_vendor), corporate_relevance = if(application_name_normalized in ("vmware workstation", "vmware workstation pro"), "Guest environments; review guest patching, virtual networking, images and asset visibility.", corporate_relevance), review_priority = if(application_name_normalized in ("vmware workstation", "vmware workstation pro"), "POLICY_DEPENDENT_UNASSIGNED", review_priority)
| alter detected_product = if(application_name_normalized = "parallels desktop", "Parallels Desktop", detected_product), product_id = if(application_name_normalized = "parallels desktop", "parallels-desktop", product_id), tool_family = if(application_name_normalized = "parallels desktop", "Virtualization", tool_family), tool_subcategory = if(application_name_normalized = "parallels desktop", "desktop-hypervisor", tool_subcategory), expected_product_vendor = if(application_name_normalized = "parallels desktop", "Parallels / Alludo", expected_product_vendor), corporate_relevance = if(application_name_normalized = "parallels desktop", "Guest environments; review guest patching, virtual networking, images and asset visibility.", corporate_relevance), review_priority = if(application_name_normalized = "parallels desktop", "POLICY_DEPENDENT_UNASSIGNED", review_priority)
| alter detected_product = if(application_name_normalized = "qemu", "QEMU", detected_product), product_id = if(application_name_normalized = "qemu", "qemu", product_id), tool_family = if(application_name_normalized = "qemu", "Virtualization", tool_family), tool_subcategory = if(application_name_normalized = "qemu", "emulation-virtualization", tool_subcategory), expected_product_vendor = if(application_name_normalized = "qemu", "QEMU project", expected_product_vendor), corporate_relevance = if(application_name_normalized = "qemu", "Guest environments; review guest patching, virtual networking, images and asset visibility.", corporate_relevance), review_priority = if(application_name_normalized = "qemu", "POLICY_DEPENDENT_UNASSIGNED", review_priority)
| filter product_id != "UNMAPPED"
| fields endpoint_name, platform, application_name, version, application_name_normalized, detected_product, product_id, tool_family, tool_subcategory, expected_product_vendor, corporate_relevance, review_priority
| limit 1000
