config case_sensitive = false timeframe = 30d
| preset = host_inventory_applications
| filter application_name != null and application_name != ""
| fields endpoint_name, platform, application_name, version
| alter application_name_normalized = lowercase(application_name)
| filter application_name_normalized in ("avast free antivirus", "avg antivirus free", "eset nod32 antivirus", "clamav")
| alter detected_product = "UNMAPPED", product_id = "UNMAPPED", tool_family = "UNMAPPED", tool_subcategory = "UNMAPPED", expected_product_vendor = "UNMAPPED", corporate_relevance = "UNMAPPED", review_priority = "UNMAPPED"
| alter detected_product = if(application_name_normalized = "avast free antivirus", "Avast Free Antivirus", detected_product), product_id = if(application_name_normalized = "avast free antivirus", "avast-free-antivirus", product_id), tool_family = if(application_name_normalized = "avast free antivirus", "Antivirus", tool_family), tool_subcategory = if(application_name_normalized = "avast free antivirus", "consumer-antivirus", tool_subcategory), expected_product_vendor = if(application_name_normalized = "avast free antivirus", "Avast / Gen Digital", expected_product_vendor), corporate_relevance = if(application_name_normalized = "avast free antivirus", "Malware protection; verify management, update state and coexistence separately from installation.", corporate_relevance), review_priority = if(application_name_normalized = "avast free antivirus", "POLICY_DEPENDENT_UNASSIGNED", review_priority)
| alter detected_product = if(application_name_normalized = "avg antivirus free", "AVG AntiVirus FREE", detected_product), product_id = if(application_name_normalized = "avg antivirus free", "avg-antivirus-free", product_id), tool_family = if(application_name_normalized = "avg antivirus free", "Antivirus", tool_family), tool_subcategory = if(application_name_normalized = "avg antivirus free", "consumer-antivirus", tool_subcategory), expected_product_vendor = if(application_name_normalized = "avg antivirus free", "AVG / Gen Digital", expected_product_vendor), corporate_relevance = if(application_name_normalized = "avg antivirus free", "Malware protection; verify management, update state and coexistence separately from installation.", corporate_relevance), review_priority = if(application_name_normalized = "avg antivirus free", "POLICY_DEPENDENT_UNASSIGNED", review_priority)
| alter detected_product = if(application_name_normalized = "eset nod32 antivirus", "ESET NOD32 Antivirus", detected_product), product_id = if(application_name_normalized = "eset nod32 antivirus", "eset-nod32", product_id), tool_family = if(application_name_normalized = "eset nod32 antivirus", "Antivirus", tool_family), tool_subcategory = if(application_name_normalized = "eset nod32 antivirus", "antivirus", tool_subcategory), expected_product_vendor = if(application_name_normalized = "eset nod32 antivirus", "ESET", expected_product_vendor), corporate_relevance = if(application_name_normalized = "eset nod32 antivirus", "Malware protection; verify management, update state and coexistence separately from installation.", corporate_relevance), review_priority = if(application_name_normalized = "eset nod32 antivirus", "POLICY_DEPENDENT_UNASSIGNED", review_priority)
| alter detected_product = if(application_name_normalized = "clamav", "ClamAV", detected_product), product_id = if(application_name_normalized = "clamav", "clamav", product_id), tool_family = if(application_name_normalized = "clamav", "Antivirus", tool_family), tool_subcategory = if(application_name_normalized = "clamav", "antivirus-engine", tool_subcategory), expected_product_vendor = if(application_name_normalized = "clamav", "Cisco / ClamAV contributors", expected_product_vendor), corporate_relevance = if(application_name_normalized = "clamav", "Malware protection; verify management, update state and coexistence separately from installation.", corporate_relevance), review_priority = if(application_name_normalized = "clamav", "POLICY_DEPENDENT_UNASSIGNED", review_priority)
| filter product_id != "UNMAPPED"
| fields endpoint_name, platform, application_name, version, application_name_normalized, detected_product, product_id, tool_family, tool_subcategory, expected_product_vendor, corporate_relevance, review_priority
| limit 1000
