config case_sensitive = false timeframe = 30d
| preset = host_inventory_applications
| filter application_name != null and application_name != ""
| fields endpoint_name, platform, application_name, version
| alter application_name_normalized = lowercase(application_name)
| filter application_name_normalized in ("xmrig", "nicehash miner", "electrum", "bitcoin core")
| alter detected_product = "UNMAPPED", product_id = "UNMAPPED", tool_family = "UNMAPPED", tool_subcategory = "UNMAPPED", expected_product_vendor = "UNMAPPED", corporate_relevance = "UNMAPPED", review_priority = "UNMAPPED"
| alter detected_product = if(application_name_normalized = "xmrig", "XMRig", detected_product), product_id = if(application_name_normalized = "xmrig", "xmrig", product_id), tool_family = if(application_name_normalized = "xmrig", "Crypto / Mining Tools", tool_family), tool_subcategory = if(application_name_normalized = "xmrig", "mining-software", tool_subcategory), expected_product_vendor = if(application_name_normalized = "xmrig", "XMRig contributors", expected_product_vendor), corporate_relevance = if(application_name_normalized = "xmrig", "Wallets and resource-intensive mining; review business purpose, custody, resource allocation and policy.", corporate_relevance), review_priority = if(application_name_normalized = "xmrig", "POLICY_DEPENDENT_UNASSIGNED", review_priority)
| alter detected_product = if(application_name_normalized = "nicehash miner", "NiceHash Miner", detected_product), product_id = if(application_name_normalized = "nicehash miner", "nicehash-miner", product_id), tool_family = if(application_name_normalized = "nicehash miner", "Crypto / Mining Tools", tool_family), tool_subcategory = if(application_name_normalized = "nicehash miner", "mining-software", tool_subcategory), expected_product_vendor = if(application_name_normalized = "nicehash miner", "NiceHash", expected_product_vendor), corporate_relevance = if(application_name_normalized = "nicehash miner", "Wallets and resource-intensive mining; review business purpose, custody, resource allocation and policy.", corporate_relevance), review_priority = if(application_name_normalized = "nicehash miner", "POLICY_DEPENDENT_UNASSIGNED", review_priority)
| alter detected_product = if(application_name_normalized = "electrum", "Electrum", detected_product), product_id = if(application_name_normalized = "electrum", "electrum", product_id), tool_family = if(application_name_normalized = "electrum", "Crypto / Mining Tools", tool_family), tool_subcategory = if(application_name_normalized = "electrum", "cryptocurrency-wallet", tool_subcategory), expected_product_vendor = if(application_name_normalized = "electrum", "Electrum developers", expected_product_vendor), corporate_relevance = if(application_name_normalized = "electrum", "Wallets and resource-intensive mining; review business purpose, custody, resource allocation and policy.", corporate_relevance), review_priority = if(application_name_normalized = "electrum", "POLICY_DEPENDENT_UNASSIGNED", review_priority)
| alter detected_product = if(application_name_normalized = "bitcoin core", "Bitcoin Core", detected_product), product_id = if(application_name_normalized = "bitcoin core", "bitcoin-core", product_id), tool_family = if(application_name_normalized = "bitcoin core", "Crypto / Mining Tools", tool_family), tool_subcategory = if(application_name_normalized = "bitcoin core", "cryptocurrency-node-wallet", tool_subcategory), expected_product_vendor = if(application_name_normalized = "bitcoin core", "Bitcoin Core contributors", expected_product_vendor), corporate_relevance = if(application_name_normalized = "bitcoin core", "Wallets and resource-intensive mining; review business purpose, custody, resource allocation and policy.", corporate_relevance), review_priority = if(application_name_normalized = "bitcoin core", "POLICY_DEPENDENT_UNASSIGNED", review_priority)
| filter product_id != "UNMAPPED"
| fields endpoint_name, platform, application_name, version, application_name_normalized, detected_product, product_id, tool_family, tool_subcategory, expected_product_vendor, corporate_relevance, review_priority
| limit 1000
