config case_sensitive = false timeframe = 30d
| preset = host_inventory_applications
| filter application_name != null and application_name != ""
| fields endpoint_name, platform, application_name, version
| alter application_name_normalized = lowercase(application_name)
| filter application_name_normalized in ("ccleaner", "revo uninstaller", "revo uninstaller pro", "internet download manager", "bluestacks", "bluestacks app player")
| alter detected_product = "UNMAPPED", product_id = "UNMAPPED", tool_family = "UNMAPPED", tool_subcategory = "UNMAPPED", expected_product_vendor = "UNMAPPED", corporate_relevance = "UNMAPPED", review_priority = "UNMAPPED"
| alter detected_product = if(application_name_normalized = "ccleaner", "CCleaner", detected_product), product_id = if(application_name_normalized = "ccleaner", "ccleaner", product_id), tool_family = if(application_name_normalized = "ccleaner", "Other Corporate-Risk / Shadow-IT Applications", tool_family), tool_subcategory = if(application_name_normalized = "ccleaner", "system-optimization", tool_subcategory), expected_product_vendor = if(application_name_normalized = "ccleaner", "Piriform / Gen Digital", expected_product_vendor), corporate_relevance = if(application_name_normalized = "ccleaner", "Additional policy review candidates; category membership never establishes that an application is unauthorized.", corporate_relevance), review_priority = if(application_name_normalized = "ccleaner", "POLICY_DEPENDENT_UNASSIGNED", review_priority)
| alter detected_product = if(application_name_normalized in ("revo uninstaller", "revo uninstaller pro"), "Revo Uninstaller", detected_product), product_id = if(application_name_normalized in ("revo uninstaller", "revo uninstaller pro"), "revo-uninstaller", product_id), tool_family = if(application_name_normalized in ("revo uninstaller", "revo uninstaller pro"), "Other Corporate-Risk / Shadow-IT Applications", tool_family), tool_subcategory = if(application_name_normalized in ("revo uninstaller", "revo uninstaller pro"), "software-removal", tool_subcategory), expected_product_vendor = if(application_name_normalized in ("revo uninstaller", "revo uninstaller pro"), "VS Revo Group", expected_product_vendor), corporate_relevance = if(application_name_normalized in ("revo uninstaller", "revo uninstaller pro"), "Additional policy review candidates; category membership never establishes that an application is unauthorized.", corporate_relevance), review_priority = if(application_name_normalized in ("revo uninstaller", "revo uninstaller pro"), "POLICY_DEPENDENT_UNASSIGNED", review_priority)
| alter detected_product = if(application_name_normalized = "internet download manager", "Internet Download Manager", detected_product), product_id = if(application_name_normalized = "internet download manager", "internet-download-manager", product_id), tool_family = if(application_name_normalized = "internet download manager", "Other Corporate-Risk / Shadow-IT Applications", tool_family), tool_subcategory = if(application_name_normalized = "internet download manager", "download-manager", tool_subcategory), expected_product_vendor = if(application_name_normalized = "internet download manager", "Tonec", expected_product_vendor), corporate_relevance = if(application_name_normalized = "internet download manager", "Additional policy review candidates; category membership never establishes that an application is unauthorized.", corporate_relevance), review_priority = if(application_name_normalized = "internet download manager", "POLICY_DEPENDENT_UNASSIGNED", review_priority)
| alter detected_product = if(application_name_normalized in ("bluestacks", "bluestacks app player"), "BlueStacks", detected_product), product_id = if(application_name_normalized in ("bluestacks", "bluestacks app player"), "bluestacks", product_id), tool_family = if(application_name_normalized in ("bluestacks", "bluestacks app player"), "Other Corporate-Risk / Shadow-IT Applications", tool_family), tool_subcategory = if(application_name_normalized in ("bluestacks", "bluestacks app player"), "mobile-app-emulation", tool_subcategory), expected_product_vendor = if(application_name_normalized in ("bluestacks", "bluestacks app player"), "BlueStacks", expected_product_vendor), corporate_relevance = if(application_name_normalized in ("bluestacks", "bluestacks app player"), "Additional policy review candidates; category membership never establishes that an application is unauthorized.", corporate_relevance), review_priority = if(application_name_normalized in ("bluestacks", "bluestacks app player"), "POLICY_DEPENDENT_UNASSIGNED", review_priority)
| filter product_id != "UNMAPPED"
| fields endpoint_name, platform, application_name, version, application_name_normalized, detected_product, product_id, tool_family, tool_subcategory, expected_product_vendor, corporate_relevance, review_priority
| limit 1000
