config case_sensitive = false timeframe = 30d
| preset = host_inventory_applications
| filter application_name != null and application_name != ""
| fields endpoint_name, platform, application_name, version
| alter application_name_normalized = lowercase(application_name)
| filter application_name_normalized in ("teamviewer", "teamviewer host", "teamviewer quicksupport", "anydesk", "rustdesk", "screenconnect", "screenconnect client", "connectwise control", "realvnc connect", "realvnc server", "realvnc viewer")
| alter detected_product = "UNMAPPED", product_id = "UNMAPPED", tool_family = "UNMAPPED", tool_subcategory = "UNMAPPED", expected_product_vendor = "UNMAPPED", corporate_relevance = "UNMAPPED", review_priority = "UNMAPPED"
| alter detected_product = if(application_name_normalized in ("teamviewer", "teamviewer host", "teamviewer quicksupport"), "TeamViewer Remote", detected_product), product_id = if(application_name_normalized in ("teamviewer", "teamviewer host", "teamviewer quicksupport"), "teamviewer", product_id), tool_family = if(application_name_normalized in ("teamviewer", "teamviewer host", "teamviewer quicksupport"), "Remote Access / Remote Administration", tool_family), tool_subcategory = if(application_name_normalized in ("teamviewer", "teamviewer host", "teamviewer quicksupport"), "remote-support", tool_subcategory), expected_product_vendor = if(application_name_normalized in ("teamviewer", "teamviewer host", "teamviewer quicksupport"), "TeamViewer", expected_product_vendor), corporate_relevance = if(application_name_normalized in ("teamviewer", "teamviewer host", "teamviewer quicksupport"), "Support and administration; review access ownership, unattended access, authentication and session logging.", corporate_relevance), review_priority = if(application_name_normalized in ("teamviewer", "teamviewer host", "teamviewer quicksupport"), "POLICY_DEPENDENT_UNASSIGNED", review_priority)
| alter detected_product = if(application_name_normalized = "anydesk", "AnyDesk", detected_product), product_id = if(application_name_normalized = "anydesk", "anydesk", product_id), tool_family = if(application_name_normalized = "anydesk", "Remote Access / Remote Administration", tool_family), tool_subcategory = if(application_name_normalized = "anydesk", "remote-support", tool_subcategory), expected_product_vendor = if(application_name_normalized = "anydesk", "AnyDesk Software", expected_product_vendor), corporate_relevance = if(application_name_normalized = "anydesk", "Support and administration; review access ownership, unattended access, authentication and session logging.", corporate_relevance), review_priority = if(application_name_normalized = "anydesk", "POLICY_DEPENDENT_UNASSIGNED", review_priority)
| alter detected_product = if(application_name_normalized = "rustdesk", "RustDesk", detected_product), product_id = if(application_name_normalized = "rustdesk", "rustdesk", product_id), tool_family = if(application_name_normalized = "rustdesk", "Remote Access / Remote Administration", tool_family), tool_subcategory = if(application_name_normalized = "rustdesk", "remote-support", tool_subcategory), expected_product_vendor = if(application_name_normalized = "rustdesk", "RustDesk project", expected_product_vendor), corporate_relevance = if(application_name_normalized = "rustdesk", "Support and administration; review access ownership, unattended access, authentication and session logging.", corporate_relevance), review_priority = if(application_name_normalized = "rustdesk", "POLICY_DEPENDENT_UNASSIGNED", review_priority)
| alter detected_product = if(application_name_normalized in ("screenconnect", "screenconnect client", "connectwise control"), "ScreenConnect", detected_product), product_id = if(application_name_normalized in ("screenconnect", "screenconnect client", "connectwise control"), "screenconnect", product_id), tool_family = if(application_name_normalized in ("screenconnect", "screenconnect client", "connectwise control"), "Remote Access / Remote Administration", tool_family), tool_subcategory = if(application_name_normalized in ("screenconnect", "screenconnect client", "connectwise control"), "remote-support", tool_subcategory), expected_product_vendor = if(application_name_normalized in ("screenconnect", "screenconnect client", "connectwise control"), "ConnectWise", expected_product_vendor), corporate_relevance = if(application_name_normalized in ("screenconnect", "screenconnect client", "connectwise control"), "Support and administration; review access ownership, unattended access, authentication and session logging.", corporate_relevance), review_priority = if(application_name_normalized in ("screenconnect", "screenconnect client", "connectwise control"), "POLICY_DEPENDENT_UNASSIGNED", review_priority)
| alter detected_product = if(application_name_normalized in ("realvnc connect", "realvnc server", "realvnc viewer"), "RealVNC Connect", detected_product), product_id = if(application_name_normalized in ("realvnc connect", "realvnc server", "realvnc viewer"), "realvnc-connect", product_id), tool_family = if(application_name_normalized in ("realvnc connect", "realvnc server", "realvnc viewer"), "Remote Access / Remote Administration", tool_family), tool_subcategory = if(application_name_normalized in ("realvnc connect", "realvnc server", "realvnc viewer"), "remote-desktop", tool_subcategory), expected_product_vendor = if(application_name_normalized in ("realvnc connect", "realvnc server", "realvnc viewer"), "RealVNC", expected_product_vendor), corporate_relevance = if(application_name_normalized in ("realvnc connect", "realvnc server", "realvnc viewer"), "Support and administration; review access ownership, unattended access, authentication and session logging.", corporate_relevance), review_priority = if(application_name_normalized in ("realvnc connect", "realvnc server", "realvnc viewer"), "POLICY_DEPENDENT_UNASSIGNED", review_priority)
| filter product_id != "UNMAPPED"
| fields endpoint_name, platform, application_name, version, application_name_normalized, detected_product, product_id, tool_family, tool_subcategory, expected_product_vendor, corporate_relevance, review_priority
| limit 1000
