config case_sensitive = false timeframe = 30d
| preset = host_inventory_applications
| filter application_name != null and application_name != ""
| fields endpoint_name, platform, application_name, version
| alter application_name_normalized = lowercase(application_name)
| filter application_name_normalized in ("steam", "epic games launcher", "gog galaxy", "battle.net", "blizzard battle.net")
| alter detected_product = "UNMAPPED", product_id = "UNMAPPED", tool_family = "UNMAPPED", tool_subcategory = "UNMAPPED", expected_product_vendor = "UNMAPPED", corporate_relevance = "UNMAPPED", review_priority = "UNMAPPED"
| alter detected_product = if(application_name_normalized = "steam", "Steam", detected_product), product_id = if(application_name_normalized = "steam", "steam", product_id), tool_family = if(application_name_normalized = "steam", "Gaming Platforms", tool_family), tool_subcategory = if(application_name_normalized = "steam", "game-distribution", tool_subcategory), expected_product_vendor = if(application_name_normalized = "steam", "Valve", expected_product_vendor), corporate_relevance = if(application_name_normalized = "steam", "Gaming and distribution; assess business justification, background updates and resource consumption.", corporate_relevance), review_priority = if(application_name_normalized = "steam", "POLICY_DEPENDENT_UNASSIGNED", review_priority)
| alter detected_product = if(application_name_normalized = "epic games launcher", "Epic Games Launcher", detected_product), product_id = if(application_name_normalized = "epic games launcher", "epic-games-launcher", product_id), tool_family = if(application_name_normalized = "epic games launcher", "Gaming Platforms", tool_family), tool_subcategory = if(application_name_normalized = "epic games launcher", "game-distribution", tool_subcategory), expected_product_vendor = if(application_name_normalized = "epic games launcher", "Epic Games", expected_product_vendor), corporate_relevance = if(application_name_normalized = "epic games launcher", "Gaming and distribution; assess business justification, background updates and resource consumption.", corporate_relevance), review_priority = if(application_name_normalized = "epic games launcher", "POLICY_DEPENDENT_UNASSIGNED", review_priority)
| alter detected_product = if(application_name_normalized = "gog galaxy", "GOG GALAXY", detected_product), product_id = if(application_name_normalized = "gog galaxy", "gog-galaxy", product_id), tool_family = if(application_name_normalized = "gog galaxy", "Gaming Platforms", tool_family), tool_subcategory = if(application_name_normalized = "gog galaxy", "game-distribution", tool_subcategory), expected_product_vendor = if(application_name_normalized = "gog galaxy", "GOG", expected_product_vendor), corporate_relevance = if(application_name_normalized = "gog galaxy", "Gaming and distribution; assess business justification, background updates and resource consumption.", corporate_relevance), review_priority = if(application_name_normalized = "gog galaxy", "POLICY_DEPENDENT_UNASSIGNED", review_priority)
| alter detected_product = if(application_name_normalized in ("battle.net", "blizzard battle.net"), "Battle.net", detected_product), product_id = if(application_name_normalized in ("battle.net", "blizzard battle.net"), "battle-net", product_id), tool_family = if(application_name_normalized in ("battle.net", "blizzard battle.net"), "Gaming Platforms", tool_family), tool_subcategory = if(application_name_normalized in ("battle.net", "blizzard battle.net"), "game-distribution", tool_subcategory), expected_product_vendor = if(application_name_normalized in ("battle.net", "blizzard battle.net"), "Blizzard Entertainment", expected_product_vendor), corporate_relevance = if(application_name_normalized in ("battle.net", "blizzard battle.net"), "Gaming and distribution; assess business justification, background updates and resource consumption.", corporate_relevance), review_priority = if(application_name_normalized in ("battle.net", "blizzard battle.net"), "POLICY_DEPENDENT_UNASSIGNED", review_priority)
| filter product_id != "UNMAPPED"
| fields endpoint_name, platform, application_name, version, application_name_normalized, detected_product, product_id, tool_family, tool_subcategory, expected_product_vendor, corporate_relevance, review_priority
| limit 1000
