config case_sensitive = false timeframe = 30d
| preset = host_inventory_applications
| filter application_name != null and application_name != ""
| fields endpoint_name, platform, application_name, version
| alter application_name_normalized = lowercase(application_name)
| filter application_name_normalized in ("notion", "obsidian", "evernote", "joplin")
| alter detected_product = "UNMAPPED", product_id = "UNMAPPED", tool_family = "UNMAPPED", tool_subcategory = "UNMAPPED", expected_product_vendor = "UNMAPPED", corporate_relevance = "UNMAPPED", review_priority = "UNMAPPED"
| alter detected_product = if(application_name_normalized = "notion", "Notion", detected_product), product_id = if(application_name_normalized = "notion", "notion", product_id), tool_family = if(application_name_normalized = "notion", "Personal Collaboration Tools", tool_family), tool_subcategory = if(application_name_normalized = "notion", "workspace-notes", tool_subcategory), expected_product_vendor = if(application_name_normalized = "notion", "Notion Labs", expected_product_vendor), corporate_relevance = if(application_name_normalized = "notion", "Notes and collaboration; review workspace ownership, guest sharing, retention and data location.", corporate_relevance), review_priority = if(application_name_normalized = "notion", "POLICY_DEPENDENT_UNASSIGNED", review_priority)
| alter detected_product = if(application_name_normalized = "obsidian", "Obsidian", detected_product), product_id = if(application_name_normalized = "obsidian", "obsidian", product_id), tool_family = if(application_name_normalized = "obsidian", "Personal Collaboration Tools", tool_family), tool_subcategory = if(application_name_normalized = "obsidian", "local-notes", tool_subcategory), expected_product_vendor = if(application_name_normalized = "obsidian", "Dynalist", expected_product_vendor), corporate_relevance = if(application_name_normalized = "obsidian", "Notes and collaboration; review workspace ownership, guest sharing, retention and data location.", corporate_relevance), review_priority = if(application_name_normalized = "obsidian", "POLICY_DEPENDENT_UNASSIGNED", review_priority)
| alter detected_product = if(application_name_normalized = "evernote", "Evernote", detected_product), product_id = if(application_name_normalized = "evernote", "evernote", product_id), tool_family = if(application_name_normalized = "evernote", "Personal Collaboration Tools", tool_family), tool_subcategory = if(application_name_normalized = "evernote", "notes-sync", tool_subcategory), expected_product_vendor = if(application_name_normalized = "evernote", "Evernote / Bending Spoons", expected_product_vendor), corporate_relevance = if(application_name_normalized = "evernote", "Notes and collaboration; review workspace ownership, guest sharing, retention and data location.", corporate_relevance), review_priority = if(application_name_normalized = "evernote", "POLICY_DEPENDENT_UNASSIGNED", review_priority)
| alter detected_product = if(application_name_normalized = "joplin", "Joplin", detected_product), product_id = if(application_name_normalized = "joplin", "joplin", product_id), tool_family = if(application_name_normalized = "joplin", "Personal Collaboration Tools", tool_family), tool_subcategory = if(application_name_normalized = "joplin", "notes-sync", tool_subcategory), expected_product_vendor = if(application_name_normalized = "joplin", "Joplin project", expected_product_vendor), corporate_relevance = if(application_name_normalized = "joplin", "Notes and collaboration; review workspace ownership, guest sharing, retention and data location.", corporate_relevance), review_priority = if(application_name_normalized = "joplin", "POLICY_DEPENDENT_UNASSIGNED", review_priority)
| filter product_id != "UNMAPPED"
| fields endpoint_name, platform, application_name, version, application_name_normalized, detected_product, product_id, tool_family, tool_subcategory, expected_product_vendor, corporate_relevance, review_priority
| limit 1000
