config case_sensitive = false timeframe = 30d
| preset = host_inventory_applications
| filter application_name != null and application_name != ""
| fields endpoint_name, platform, application_name, version
| alter application_name_normalized = lowercase(application_name)
| filter application_name_normalized in ("microsoft visual studio code", "visual studio code", "intellij idea", "intellij idea community edition", "intellij idea ultimate edition", "pycharm", "pycharm community edition", "pycharm professional edition", "sublime text")
| alter detected_product = "UNMAPPED", product_id = "UNMAPPED", tool_family = "UNMAPPED", tool_subcategory = "UNMAPPED", expected_product_vendor = "UNMAPPED", corporate_relevance = "UNMAPPED", review_priority = "UNMAPPED"
| alter detected_product = if(application_name_normalized in ("microsoft visual studio code", "visual studio code"), "Visual Studio Code", detected_product), product_id = if(application_name_normalized in ("microsoft visual studio code", "visual studio code"), "visual-studio-code", product_id), tool_family = if(application_name_normalized in ("microsoft visual studio code", "visual studio code"), "Development Tools / IDEs", tool_family), tool_subcategory = if(application_name_normalized in ("microsoft visual studio code", "visual studio code"), "code-editor", tool_subcategory), expected_product_vendor = if(application_name_normalized in ("microsoft visual studio code", "visual studio code"), "Microsoft", expected_product_vendor), corporate_relevance = if(application_name_normalized in ("microsoft visual studio code", "visual studio code"), "Software engineering; review extensions, supported versions, code trust and approved development scope.", corporate_relevance), review_priority = if(application_name_normalized in ("microsoft visual studio code", "visual studio code"), "POLICY_DEPENDENT_UNASSIGNED", review_priority)
| alter detected_product = if(application_name_normalized in ("intellij idea", "intellij idea community edition", "intellij idea ultimate edition"), "IntelliJ IDEA", detected_product), product_id = if(application_name_normalized in ("intellij idea", "intellij idea community edition", "intellij idea ultimate edition"), "intellij-idea", product_id), tool_family = if(application_name_normalized in ("intellij idea", "intellij idea community edition", "intellij idea ultimate edition"), "Development Tools / IDEs", tool_family), tool_subcategory = if(application_name_normalized in ("intellij idea", "intellij idea community edition", "intellij idea ultimate edition"), "integrated-development", tool_subcategory), expected_product_vendor = if(application_name_normalized in ("intellij idea", "intellij idea community edition", "intellij idea ultimate edition"), "JetBrains", expected_product_vendor), corporate_relevance = if(application_name_normalized in ("intellij idea", "intellij idea community edition", "intellij idea ultimate edition"), "Software engineering; review extensions, supported versions, code trust and approved development scope.", corporate_relevance), review_priority = if(application_name_normalized in ("intellij idea", "intellij idea community edition", "intellij idea ultimate edition"), "POLICY_DEPENDENT_UNASSIGNED", review_priority)
| alter detected_product = if(application_name_normalized in ("pycharm", "pycharm community edition", "pycharm professional edition"), "PyCharm", detected_product), product_id = if(application_name_normalized in ("pycharm", "pycharm community edition", "pycharm professional edition"), "pycharm", product_id), tool_family = if(application_name_normalized in ("pycharm", "pycharm community edition", "pycharm professional edition"), "Development Tools / IDEs", tool_family), tool_subcategory = if(application_name_normalized in ("pycharm", "pycharm community edition", "pycharm professional edition"), "python-ide", tool_subcategory), expected_product_vendor = if(application_name_normalized in ("pycharm", "pycharm community edition", "pycharm professional edition"), "JetBrains", expected_product_vendor), corporate_relevance = if(application_name_normalized in ("pycharm", "pycharm community edition", "pycharm professional edition"), "Software engineering; review extensions, supported versions, code trust and approved development scope.", corporate_relevance), review_priority = if(application_name_normalized in ("pycharm", "pycharm community edition", "pycharm professional edition"), "POLICY_DEPENDENT_UNASSIGNED", review_priority)
| alter detected_product = if(application_name_normalized = "sublime text", "Sublime Text", detected_product), product_id = if(application_name_normalized = "sublime text", "sublime-text", product_id), tool_family = if(application_name_normalized = "sublime text", "Development Tools / IDEs", tool_family), tool_subcategory = if(application_name_normalized = "sublime text", "code-editor", tool_subcategory), expected_product_vendor = if(application_name_normalized = "sublime text", "Sublime HQ", expected_product_vendor), corporate_relevance = if(application_name_normalized = "sublime text", "Software engineering; review extensions, supported versions, code trust and approved development scope.", corporate_relevance), review_priority = if(application_name_normalized = "sublime text", "POLICY_DEPENDENT_UNASSIGNED", review_priority)
| filter product_id != "UNMAPPED"
| fields endpoint_name, platform, application_name, version, application_name_normalized, detected_product, product_id, tool_family, tool_subcategory, expected_product_vendor, corporate_relevance, review_priority
| limit 1000
