config case_sensitive = false timeframe = 30d
| preset = host_inventory_applications
| filter application_name != null and application_name != ""
| fields endpoint_name, platform, application_name, version
| alter application_name_normalized = lowercase(application_name)
| filter application_name_normalized in ("docker desktop", "podman desktop", "rancher desktop", "minikube")
| alter detected_product = "UNMAPPED", product_id = "UNMAPPED", tool_family = "UNMAPPED", tool_subcategory = "UNMAPPED", expected_product_vendor = "UNMAPPED", corporate_relevance = "UNMAPPED", review_priority = "UNMAPPED"
| alter detected_product = if(application_name_normalized = "docker desktop", "Docker Desktop", detected_product), product_id = if(application_name_normalized = "docker desktop", "docker-desktop", product_id), tool_family = if(application_name_normalized = "docker desktop", "Containers", tool_family), tool_subcategory = if(application_name_normalized = "docker desktop", "container-desktop", tool_subcategory), expected_product_vendor = if(application_name_normalized = "docker desktop", "Docker", expected_product_vendor), corporate_relevance = if(application_name_normalized = "docker desktop", "Container workloads; review registries, image provenance, daemon permissions and host integration.", corporate_relevance), review_priority = if(application_name_normalized = "docker desktop", "POLICY_DEPENDENT_UNASSIGNED", review_priority)
| alter detected_product = if(application_name_normalized = "podman desktop", "Podman Desktop", detected_product), product_id = if(application_name_normalized = "podman desktop", "podman-desktop", product_id), tool_family = if(application_name_normalized = "podman desktop", "Containers", tool_family), tool_subcategory = if(application_name_normalized = "podman desktop", "container-desktop", tool_subcategory), expected_product_vendor = if(application_name_normalized = "podman desktop", "Podman Desktop community", expected_product_vendor), corporate_relevance = if(application_name_normalized = "podman desktop", "Container workloads; review registries, image provenance, daemon permissions and host integration.", corporate_relevance), review_priority = if(application_name_normalized = "podman desktop", "POLICY_DEPENDENT_UNASSIGNED", review_priority)
| alter detected_product = if(application_name_normalized = "rancher desktop", "Rancher Desktop", detected_product), product_id = if(application_name_normalized = "rancher desktop", "rancher-desktop", product_id), tool_family = if(application_name_normalized = "rancher desktop", "Containers", tool_family), tool_subcategory = if(application_name_normalized = "rancher desktop", "container-desktop", tool_subcategory), expected_product_vendor = if(application_name_normalized = "rancher desktop", "SUSE / Rancher", expected_product_vendor), corporate_relevance = if(application_name_normalized = "rancher desktop", "Container workloads; review registries, image provenance, daemon permissions and host integration.", corporate_relevance), review_priority = if(application_name_normalized = "rancher desktop", "POLICY_DEPENDENT_UNASSIGNED", review_priority)
| alter detected_product = if(application_name_normalized = "minikube", "minikube", detected_product), product_id = if(application_name_normalized = "minikube", "minikube", product_id), tool_family = if(application_name_normalized = "minikube", "Containers", tool_family), tool_subcategory = if(application_name_normalized = "minikube", "local-kubernetes", tool_subcategory), expected_product_vendor = if(application_name_normalized = "minikube", "Kubernetes contributors", expected_product_vendor), corporate_relevance = if(application_name_normalized = "minikube", "Container workloads; review registries, image provenance, daemon permissions and host integration.", corporate_relevance), review_priority = if(application_name_normalized = "minikube", "POLICY_DEPENDENT_UNASSIGNED", review_priority)
| filter product_id != "UNMAPPED"
| fields endpoint_name, platform, application_name, version, application_name_normalized, detected_product, product_id, tool_family, tool_subcategory, expected_product_vendor, corporate_relevance, review_priority
| limit 1000
