config case_sensitive = false timeframe = 30d
| preset = host_inventory_applications
| filter application_name != null and application_name != ""
| fields endpoint_name, platform, application_name, version
| alter application_name_normalized = lowercase(application_name)
| filter application_name_normalized in ("windows admin center", "sysinternals suite", "microsoft powertoys", "powertoys", "pdq deploy")
| alter detected_product = "UNMAPPED", product_id = "UNMAPPED", tool_family = "UNMAPPED", tool_subcategory = "UNMAPPED", expected_product_vendor = "UNMAPPED", corporate_relevance = "UNMAPPED", review_priority = "UNMAPPED"
| alter detected_product = if(application_name_normalized = "windows admin center", "Windows Admin Center", detected_product), product_id = if(application_name_normalized = "windows admin center", "windows-admin-center", product_id), tool_family = if(application_name_normalized = "windows admin center", "System Administration Tools", tool_family), tool_subcategory = if(application_name_normalized = "windows admin center", "server-management", tool_subcategory), expected_product_vendor = if(application_name_normalized = "windows admin center", "Microsoft", expected_product_vendor), corporate_relevance = if(application_name_normalized = "windows admin center", "Administrative operations; review privilege, approved operators and change logging.", corporate_relevance), review_priority = if(application_name_normalized = "windows admin center", "POLICY_DEPENDENT_UNASSIGNED", review_priority)
| alter detected_product = if(application_name_normalized = "sysinternals suite", "Sysinternals Suite", detected_product), product_id = if(application_name_normalized = "sysinternals suite", "sysinternals-suite", product_id), tool_family = if(application_name_normalized = "sysinternals suite", "System Administration Tools", tool_family), tool_subcategory = if(application_name_normalized = "sysinternals suite", "administrative-utilities", tool_subcategory), expected_product_vendor = if(application_name_normalized = "sysinternals suite", "Microsoft", expected_product_vendor), corporate_relevance = if(application_name_normalized = "sysinternals suite", "Administrative operations; review privilege, approved operators and change logging.", corporate_relevance), review_priority = if(application_name_normalized = "sysinternals suite", "POLICY_DEPENDENT_UNASSIGNED", review_priority)
| alter detected_product = if(application_name_normalized in ("microsoft powertoys", "powertoys"), "Microsoft PowerToys", detected_product), product_id = if(application_name_normalized in ("microsoft powertoys", "powertoys"), "microsoft-powertoys", product_id), tool_family = if(application_name_normalized in ("microsoft powertoys", "powertoys"), "System Administration Tools", tool_family), tool_subcategory = if(application_name_normalized in ("microsoft powertoys", "powertoys"), "desktop-administration", tool_subcategory), expected_product_vendor = if(application_name_normalized in ("microsoft powertoys", "powertoys"), "Microsoft", expected_product_vendor), corporate_relevance = if(application_name_normalized in ("microsoft powertoys", "powertoys"), "Administrative operations; review privilege, approved operators and change logging.", corporate_relevance), review_priority = if(application_name_normalized in ("microsoft powertoys", "powertoys"), "POLICY_DEPENDENT_UNASSIGNED", review_priority)
| alter detected_product = if(application_name_normalized = "pdq deploy", "PDQ Deploy", detected_product), product_id = if(application_name_normalized = "pdq deploy", "pdq-deploy", product_id), tool_family = if(application_name_normalized = "pdq deploy", "System Administration Tools", tool_family), tool_subcategory = if(application_name_normalized = "pdq deploy", "software-deployment", tool_subcategory), expected_product_vendor = if(application_name_normalized = "pdq deploy", "PDQ", expected_product_vendor), corporate_relevance = if(application_name_normalized = "pdq deploy", "Administrative operations; review privilege, approved operators and change logging.", corporate_relevance), review_priority = if(application_name_normalized = "pdq deploy", "POLICY_DEPENDENT_UNASSIGNED", review_priority)
| filter product_id != "UNMAPPED"
| fields endpoint_name, platform, application_name, version, application_name_normalized, detected_product, product_id, tool_family, tool_subcategory, expected_product_vendor, corporate_relevance, review_priority
| limit 1000
