config case_sensitive = false timeframe = 30d
| preset = host_inventory_applications
| filter application_name != null and application_name != ""
| fields endpoint_name, platform, application_name, version
| alter application_name_normalized = lowercase(application_name)
| filter application_name_normalized in ("chatgpt", "claude", "jan", "anythingllm", "anythingllm desktop")
| alter detected_product = "UNMAPPED", product_id = "UNMAPPED", tool_family = "UNMAPPED", tool_subcategory = "UNMAPPED", expected_product_vendor = "UNMAPPED", corporate_relevance = "UNMAPPED", review_priority = "UNMAPPED"
| alter detected_product = if(application_name_normalized = "chatgpt", "ChatGPT desktop app", detected_product), product_id = if(application_name_normalized = "chatgpt", "chatgpt-desktop", product_id), tool_family = if(application_name_normalized = "chatgpt", "Artificial Intelligence Tools", tool_family), tool_subcategory = if(application_name_normalized = "chatgpt", "ai-assistant", tool_subcategory), expected_product_vendor = if(application_name_normalized = "chatgpt", "OpenAI", expected_product_vendor), corporate_relevance = if(application_name_normalized = "chatgpt", "AI assistance; review account tenancy, submitted data, retention and approved connectors.", corporate_relevance), review_priority = if(application_name_normalized = "chatgpt", "POLICY_DEPENDENT_UNASSIGNED", review_priority)
| alter detected_product = if(application_name_normalized = "claude", "Claude desktop app", detected_product), product_id = if(application_name_normalized = "claude", "claude-desktop", product_id), tool_family = if(application_name_normalized = "claude", "Artificial Intelligence Tools", tool_family), tool_subcategory = if(application_name_normalized = "claude", "ai-assistant", tool_subcategory), expected_product_vendor = if(application_name_normalized = "claude", "Anthropic", expected_product_vendor), corporate_relevance = if(application_name_normalized = "claude", "AI assistance; review account tenancy, submitted data, retention and approved connectors.", corporate_relevance), review_priority = if(application_name_normalized = "claude", "POLICY_DEPENDENT_UNASSIGNED", review_priority)
| alter detected_product = if(application_name_normalized = "jan", "Jan", detected_product), product_id = if(application_name_normalized = "jan", "jan", product_id), tool_family = if(application_name_normalized = "jan", "Artificial Intelligence Tools", tool_family), tool_subcategory = if(application_name_normalized = "jan", "ai-assistant", tool_subcategory), expected_product_vendor = if(application_name_normalized = "jan", "Jan project", expected_product_vendor), corporate_relevance = if(application_name_normalized = "jan", "AI assistance; review account tenancy, submitted data, retention and approved connectors.", corporate_relevance), review_priority = if(application_name_normalized = "jan", "POLICY_DEPENDENT_UNASSIGNED", review_priority)
| alter detected_product = if(application_name_normalized in ("anythingllm", "anythingllm desktop"), "AnythingLLM Desktop", detected_product), product_id = if(application_name_normalized in ("anythingllm", "anythingllm desktop"), "anythingllm", product_id), tool_family = if(application_name_normalized in ("anythingllm", "anythingllm desktop"), "Artificial Intelligence Tools", tool_family), tool_subcategory = if(application_name_normalized in ("anythingllm", "anythingllm desktop"), "ai-knowledge-assistant", tool_subcategory), expected_product_vendor = if(application_name_normalized in ("anythingllm", "anythingllm desktop"), "Mintplex Labs", expected_product_vendor), corporate_relevance = if(application_name_normalized in ("anythingllm", "anythingllm desktop"), "AI assistance; review account tenancy, submitted data, retention and approved connectors.", corporate_relevance), review_priority = if(application_name_normalized in ("anythingllm", "anythingllm desktop"), "POLICY_DEPENDENT_UNASSIGNED", review_priority)
| filter product_id != "UNMAPPED"
| fields endpoint_name, platform, application_name, version, application_name_normalized, detected_product, product_id, tool_family, tool_subcategory, expected_product_vendor, corporate_relevance, review_priority
| limit 1000
