config case_sensitive = false timeframe = 30d
| preset = host_inventory_applications
| filter application_name != null and application_name != ""
| fields endpoint_name, platform, application_name, version
| alter application_name_normalized = lowercase(application_name)
| filter application_name_normalized in ("tor browser", "i2p", "veracrypt", "cryptomator")
| alter detected_product = "UNMAPPED", product_id = "UNMAPPED", tool_family = "UNMAPPED", tool_subcategory = "UNMAPPED", expected_product_vendor = "UNMAPPED", corporate_relevance = "UNMAPPED", review_priority = "UNMAPPED"
| alter detected_product = if(application_name_normalized = "tor browser", "Tor Browser", detected_product), product_id = if(application_name_normalized = "tor browser", "tor-browser", product_id), tool_family = if(application_name_normalized = "tor browser", "Privacy / Anonymization Tools", tool_family), tool_subcategory = if(application_name_normalized = "tor browser", "anonymizing-browser", tool_subcategory), expected_product_vendor = if(application_name_normalized = "tor browser", "The Tor Project", expected_product_vendor), corporate_relevance = if(application_name_normalized = "tor browser", "Privacy and confidentiality; review routing, key recovery, approved use and access requirements.", corporate_relevance), review_priority = if(application_name_normalized = "tor browser", "POLICY_DEPENDENT_UNASSIGNED", review_priority)
| alter detected_product = if(application_name_normalized = "i2p", "I2P", detected_product), product_id = if(application_name_normalized = "i2p", "i2p", product_id), tool_family = if(application_name_normalized = "i2p", "Privacy / Anonymization Tools", tool_family), tool_subcategory = if(application_name_normalized = "i2p", "anonymizing-overlay", tool_subcategory), expected_product_vendor = if(application_name_normalized = "i2p", "I2P project", expected_product_vendor), corporate_relevance = if(application_name_normalized = "i2p", "Privacy and confidentiality; review routing, key recovery, approved use and access requirements.", corporate_relevance), review_priority = if(application_name_normalized = "i2p", "POLICY_DEPENDENT_UNASSIGNED", review_priority)
| alter detected_product = if(application_name_normalized = "veracrypt", "VeraCrypt", detected_product), product_id = if(application_name_normalized = "veracrypt", "veracrypt", product_id), tool_family = if(application_name_normalized = "veracrypt", "Privacy / Anonymization Tools", tool_family), tool_subcategory = if(application_name_normalized = "veracrypt", "file-volume-encryption", tool_subcategory), expected_product_vendor = if(application_name_normalized = "veracrypt", "IDRIX / VeraCrypt contributors", expected_product_vendor), corporate_relevance = if(application_name_normalized = "veracrypt", "Privacy and confidentiality; review routing, key recovery, approved use and access requirements.", corporate_relevance), review_priority = if(application_name_normalized = "veracrypt", "POLICY_DEPENDENT_UNASSIGNED", review_priority)
| alter detected_product = if(application_name_normalized = "cryptomator", "Cryptomator", detected_product), product_id = if(application_name_normalized = "cryptomator", "cryptomator", product_id), tool_family = if(application_name_normalized = "cryptomator", "Privacy / Anonymization Tools", tool_family), tool_subcategory = if(application_name_normalized = "cryptomator", "file-encryption", tool_subcategory), expected_product_vendor = if(application_name_normalized = "cryptomator", "Skymatic / Cryptomator contributors", expected_product_vendor), corporate_relevance = if(application_name_normalized = "cryptomator", "Privacy and confidentiality; review routing, key recovery, approved use and access requirements.", corporate_relevance), review_priority = if(application_name_normalized = "cryptomator", "POLICY_DEPENDENT_UNASSIGNED", review_priority)
| filter product_id != "UNMAPPED"
| fields endpoint_name, platform, application_name, version, application_name_normalized, detected_product, product_id, tool_family, tool_subcategory, expected_product_vendor, corporate_relevance, review_priority
| limit 1000
