config case_sensitive = false timeframe = 30d
| preset = host_inventory_applications
| filter application_name != null and application_name != ""
| fields endpoint_name, platform, application_name, version
| alter application_name_normalized = lowercase(application_name)
| filter application_name_normalized in ("globalprotect", "cisco secure client", "cisco anyconnect secure mobility client", "openvpn connect", "wireguard", "tailscale", "ngrok")
| alter detected_product = "UNMAPPED", product_id = "UNMAPPED", tool_family = "UNMAPPED", tool_subcategory = "UNMAPPED", expected_product_vendor = "UNMAPPED", corporate_relevance = "UNMAPPED", review_priority = "UNMAPPED"
| alter detected_product = if(application_name_normalized = "globalprotect", "GlobalProtect", detected_product), product_id = if(application_name_normalized = "globalprotect", "globalprotect", product_id), tool_family = if(application_name_normalized = "globalprotect", "VPN / Tunneling / Proxy", tool_family), tool_subcategory = if(application_name_normalized = "globalprotect", "enterprise-vpn", tool_subcategory), expected_product_vendor = if(application_name_normalized = "globalprotect", "Palo Alto Networks", expected_product_vendor), corporate_relevance = if(application_name_normalized = "globalprotect", "Connectivity and routing; review approved destinations, split tunneling and network-control requirements.", corporate_relevance), review_priority = if(application_name_normalized = "globalprotect", "POLICY_DEPENDENT_UNASSIGNED", review_priority)
| alter detected_product = if(application_name_normalized in ("cisco secure client", "cisco anyconnect secure mobility client"), "Cisco Secure Client", detected_product), product_id = if(application_name_normalized in ("cisco secure client", "cisco anyconnect secure mobility client"), "cisco-secure-client", product_id), tool_family = if(application_name_normalized in ("cisco secure client", "cisco anyconnect secure mobility client"), "VPN / Tunneling / Proxy", tool_family), tool_subcategory = if(application_name_normalized in ("cisco secure client", "cisco anyconnect secure mobility client"), "enterprise-connectivity", tool_subcategory), expected_product_vendor = if(application_name_normalized in ("cisco secure client", "cisco anyconnect secure mobility client"), "Cisco", expected_product_vendor), corporate_relevance = if(application_name_normalized in ("cisco secure client", "cisco anyconnect secure mobility client"), "Connectivity and routing; review approved destinations, split tunneling and network-control requirements.", corporate_relevance), review_priority = if(application_name_normalized in ("cisco secure client", "cisco anyconnect secure mobility client"), "POLICY_DEPENDENT_UNASSIGNED", review_priority)
| alter detected_product = if(application_name_normalized = "openvpn connect", "OpenVPN Connect", detected_product), product_id = if(application_name_normalized = "openvpn connect", "openvpn-connect", product_id), tool_family = if(application_name_normalized = "openvpn connect", "VPN / Tunneling / Proxy", tool_family), tool_subcategory = if(application_name_normalized = "openvpn connect", "vpn-client", tool_subcategory), expected_product_vendor = if(application_name_normalized = "openvpn connect", "OpenVPN", expected_product_vendor), corporate_relevance = if(application_name_normalized = "openvpn connect", "Connectivity and routing; review approved destinations, split tunneling and network-control requirements.", corporate_relevance), review_priority = if(application_name_normalized = "openvpn connect", "POLICY_DEPENDENT_UNASSIGNED", review_priority)
| alter detected_product = if(application_name_normalized = "wireguard", "WireGuard", detected_product), product_id = if(application_name_normalized = "wireguard", "wireguard", product_id), tool_family = if(application_name_normalized = "wireguard", "VPN / Tunneling / Proxy", tool_family), tool_subcategory = if(application_name_normalized = "wireguard", "vpn-client", tool_subcategory), expected_product_vendor = if(application_name_normalized = "wireguard", "WireGuard project", expected_product_vendor), corporate_relevance = if(application_name_normalized = "wireguard", "Connectivity and routing; review approved destinations, split tunneling and network-control requirements.", corporate_relevance), review_priority = if(application_name_normalized = "wireguard", "POLICY_DEPENDENT_UNASSIGNED", review_priority)
| alter detected_product = if(application_name_normalized = "tailscale", "Tailscale", detected_product), product_id = if(application_name_normalized = "tailscale", "tailscale", product_id), tool_family = if(application_name_normalized = "tailscale", "VPN / Tunneling / Proxy", tool_family), tool_subcategory = if(application_name_normalized = "tailscale", "mesh-connectivity", tool_subcategory), expected_product_vendor = if(application_name_normalized = "tailscale", "Tailscale", expected_product_vendor), corporate_relevance = if(application_name_normalized = "tailscale", "Connectivity and routing; review approved destinations, split tunneling and network-control requirements.", corporate_relevance), review_priority = if(application_name_normalized = "tailscale", "POLICY_DEPENDENT_UNASSIGNED", review_priority)
| alter detected_product = if(application_name_normalized = "ngrok", "ngrok", detected_product), product_id = if(application_name_normalized = "ngrok", "ngrok", product_id), tool_family = if(application_name_normalized = "ngrok", "VPN / Tunneling / Proxy", tool_family), tool_subcategory = if(application_name_normalized = "ngrok", "tunnel-service-client", tool_subcategory), expected_product_vendor = if(application_name_normalized = "ngrok", "ngrok", expected_product_vendor), corporate_relevance = if(application_name_normalized = "ngrok", "Connectivity and routing; review approved destinations, split tunneling and network-control requirements.", corporate_relevance), review_priority = if(application_name_normalized = "ngrok", "POLICY_DEPENDENT_UNASSIGNED", review_priority)
| filter product_id != "UNMAPPED"
| fields endpoint_name, platform, application_name, version, application_name_normalized, detected_product, product_id, tool_family, tool_subcategory, expected_product_vendor, corporate_relevance, review_priority
| limit 1000
