config case_sensitive = false timeframe = 30d
| preset = host_inventory_applications
| filter application_name != null and application_name != ""
| fields endpoint_name, platform, application_name, version
| alter application_name_normalized = lowercase(application_name)
| filter application_name_normalized in ("microsoft teams", "microsoft teams classic", "slack", "signal", "signal desktop", "telegram desktop", "discord")
| alter detected_product = "UNMAPPED", product_id = "UNMAPPED", tool_family = "UNMAPPED", tool_subcategory = "UNMAPPED", expected_product_vendor = "UNMAPPED", corporate_relevance = "UNMAPPED", review_priority = "UNMAPPED"
| alter detected_product = if(application_name_normalized in ("microsoft teams", "microsoft teams classic"), "Microsoft Teams", detected_product), product_id = if(application_name_normalized in ("microsoft teams", "microsoft teams classic"), "microsoft-teams", product_id), tool_family = if(application_name_normalized in ("microsoft teams", "microsoft teams classic"), "Communication / Messaging", tool_family), tool_subcategory = if(application_name_normalized in ("microsoft teams", "microsoft teams classic"), "enterprise-messaging", tool_subcategory), expected_product_vendor = if(application_name_normalized in ("microsoft teams", "microsoft teams classic"), "Microsoft", expected_product_vendor), corporate_relevance = if(application_name_normalized in ("microsoft teams", "microsoft teams classic"), "Messaging and meetings; review external participants, retention, file sharing and organizational tenancy.", corporate_relevance), review_priority = if(application_name_normalized in ("microsoft teams", "microsoft teams classic"), "POLICY_DEPENDENT_UNASSIGNED", review_priority)
| alter detected_product = if(application_name_normalized = "slack", "Slack", detected_product), product_id = if(application_name_normalized = "slack", "slack", product_id), tool_family = if(application_name_normalized = "slack", "Communication / Messaging", tool_family), tool_subcategory = if(application_name_normalized = "slack", "workspace-messaging", tool_subcategory), expected_product_vendor = if(application_name_normalized = "slack", "Slack / Salesforce", expected_product_vendor), corporate_relevance = if(application_name_normalized = "slack", "Messaging and meetings; review external participants, retention, file sharing and organizational tenancy.", corporate_relevance), review_priority = if(application_name_normalized = "slack", "POLICY_DEPENDENT_UNASSIGNED", review_priority)
| alter detected_product = if(application_name_normalized in ("signal", "signal desktop"), "Signal Desktop", detected_product), product_id = if(application_name_normalized in ("signal", "signal desktop"), "signal-desktop", product_id), tool_family = if(application_name_normalized in ("signal", "signal desktop"), "Communication / Messaging", tool_family), tool_subcategory = if(application_name_normalized in ("signal", "signal desktop"), "secure-messaging", tool_subcategory), expected_product_vendor = if(application_name_normalized in ("signal", "signal desktop"), "Signal Messenger", expected_product_vendor), corporate_relevance = if(application_name_normalized in ("signal", "signal desktop"), "Messaging and meetings; review external participants, retention, file sharing and organizational tenancy.", corporate_relevance), review_priority = if(application_name_normalized in ("signal", "signal desktop"), "POLICY_DEPENDENT_UNASSIGNED", review_priority)
| alter detected_product = if(application_name_normalized = "telegram desktop", "Telegram Desktop", detected_product), product_id = if(application_name_normalized = "telegram desktop", "telegram-desktop", product_id), tool_family = if(application_name_normalized = "telegram desktop", "Communication / Messaging", tool_family), tool_subcategory = if(application_name_normalized = "telegram desktop", "messaging", tool_subcategory), expected_product_vendor = if(application_name_normalized = "telegram desktop", "Telegram", expected_product_vendor), corporate_relevance = if(application_name_normalized = "telegram desktop", "Messaging and meetings; review external participants, retention, file sharing and organizational tenancy.", corporate_relevance), review_priority = if(application_name_normalized = "telegram desktop", "POLICY_DEPENDENT_UNASSIGNED", review_priority)
| alter detected_product = if(application_name_normalized = "discord", "Discord", detected_product), product_id = if(application_name_normalized = "discord", "discord", product_id), tool_family = if(application_name_normalized = "discord", "Communication / Messaging", tool_family), tool_subcategory = if(application_name_normalized = "discord", "community-messaging", tool_subcategory), expected_product_vendor = if(application_name_normalized = "discord", "Discord", expected_product_vendor), corporate_relevance = if(application_name_normalized = "discord", "Messaging and meetings; review external participants, retention, file sharing and organizational tenancy.", corporate_relevance), review_priority = if(application_name_normalized = "discord", "POLICY_DEPENDENT_UNASSIGNED", review_priority)
| filter product_id != "UNMAPPED"
| fields endpoint_name, platform, application_name, version, application_name_normalized, detected_product, product_id, tool_family, tool_subcategory, expected_product_vendor, corporate_relevance, review_priority
| limit 1000
