config case_sensitive = false timeframe = 30d
| preset = host_inventory_applications
| filter application_name != null and application_name != ""
| fields endpoint_name, platform, application_name, version
| alter application_name_normalized = lowercase(application_name)
| filter application_name_normalized in ("obs studio", "sharex", "snagit", "techsmith snagit", "loom")
| alter detected_product = "UNMAPPED", product_id = "UNMAPPED", tool_family = "UNMAPPED", tool_subcategory = "UNMAPPED", expected_product_vendor = "UNMAPPED", corporate_relevance = "UNMAPPED", review_priority = "UNMAPPED"
| alter detected_product = if(application_name_normalized = "obs studio", "OBS Studio", detected_product), product_id = if(application_name_normalized = "obs studio", "obs-studio", product_id), tool_family = if(application_name_normalized = "obs studio", "Screen Recording / Capture", tool_family), tool_subcategory = if(application_name_normalized = "obs studio", "screen-recording", tool_subcategory), expected_product_vendor = if(application_name_normalized = "obs studio", "OBS Project", expected_product_vendor), corporate_relevance = if(application_name_normalized = "obs studio", "Screen capture and recording; review sensitive-screen exposure, storage, sharing and consent policy.", corporate_relevance), review_priority = if(application_name_normalized = "obs studio", "POLICY_DEPENDENT_UNASSIGNED", review_priority)
| alter detected_product = if(application_name_normalized = "sharex", "ShareX", detected_product), product_id = if(application_name_normalized = "sharex", "sharex", product_id), tool_family = if(application_name_normalized = "sharex", "Screen Recording / Capture", tool_family), tool_subcategory = if(application_name_normalized = "sharex", "capture-sharing", tool_subcategory), expected_product_vendor = if(application_name_normalized = "sharex", "ShareX Team", expected_product_vendor), corporate_relevance = if(application_name_normalized = "sharex", "Screen capture and recording; review sensitive-screen exposure, storage, sharing and consent policy.", corporate_relevance), review_priority = if(application_name_normalized = "sharex", "POLICY_DEPENDENT_UNASSIGNED", review_priority)
| alter detected_product = if(application_name_normalized in ("snagit", "techsmith snagit"), "Snagit", detected_product), product_id = if(application_name_normalized in ("snagit", "techsmith snagit"), "snagit", product_id), tool_family = if(application_name_normalized in ("snagit", "techsmith snagit"), "Screen Recording / Capture", tool_family), tool_subcategory = if(application_name_normalized in ("snagit", "techsmith snagit"), "screen-capture", tool_subcategory), expected_product_vendor = if(application_name_normalized in ("snagit", "techsmith snagit"), "TechSmith", expected_product_vendor), corporate_relevance = if(application_name_normalized in ("snagit", "techsmith snagit"), "Screen capture and recording; review sensitive-screen exposure, storage, sharing and consent policy.", corporate_relevance), review_priority = if(application_name_normalized in ("snagit", "techsmith snagit"), "POLICY_DEPENDENT_UNASSIGNED", review_priority)
| alter detected_product = if(application_name_normalized = "loom", "Loom", detected_product), product_id = if(application_name_normalized = "loom", "loom", product_id), tool_family = if(application_name_normalized = "loom", "Screen Recording / Capture", tool_family), tool_subcategory = if(application_name_normalized = "loom", "screen-recording-sharing", tool_subcategory), expected_product_vendor = if(application_name_normalized = "loom", "Atlassian", expected_product_vendor), corporate_relevance = if(application_name_normalized = "loom", "Screen capture and recording; review sensitive-screen exposure, storage, sharing and consent policy.", corporate_relevance), review_priority = if(application_name_normalized = "loom", "POLICY_DEPENDENT_UNASSIGNED", review_priority)
| filter product_id != "UNMAPPED"
| fields endpoint_name, platform, application_name, version, application_name_normalized, detected_product, product_id, tool_family, tool_subcategory, expected_product_vendor, corporate_relevance, review_priority
| limit 1000
