config case_sensitive = false timeframe = 30d
| preset = host_inventory_applications
| filter application_name != null and application_name != ""
| fields endpoint_name, platform, application_name, version
| alter application_name_normalized = lowercase(application_name)
| filter application_name_normalized in ("ollama", "lm studio", "gpt4all", "llama.cpp")
| alter detected_product = "UNMAPPED", product_id = "UNMAPPED", tool_family = "UNMAPPED", tool_subcategory = "UNMAPPED", expected_product_vendor = "UNMAPPED", corporate_relevance = "UNMAPPED", review_priority = "UNMAPPED"
| alter detected_product = if(application_name_normalized = "ollama", "Ollama", detected_product), product_id = if(application_name_normalized = "ollama", "ollama", product_id), tool_family = if(application_name_normalized = "ollama", "Local AI / LLM Runtimes", tool_family), tool_subcategory = if(application_name_normalized = "ollama", "model-runtime", tool_subcategory), expected_product_vendor = if(application_name_normalized = "ollama", "Ollama", expected_product_vendor), corporate_relevance = if(application_name_normalized = "ollama", "Local model execution; review model provenance, resource use, listener exposure and optional cloud connections.", corporate_relevance), review_priority = if(application_name_normalized = "ollama", "POLICY_DEPENDENT_UNASSIGNED", review_priority)
| alter detected_product = if(application_name_normalized = "lm studio", "LM Studio", detected_product), product_id = if(application_name_normalized = "lm studio", "lm-studio", product_id), tool_family = if(application_name_normalized = "lm studio", "Local AI / LLM Runtimes", tool_family), tool_subcategory = if(application_name_normalized = "lm studio", "model-runtime", tool_subcategory), expected_product_vendor = if(application_name_normalized = "lm studio", "Element Labs", expected_product_vendor), corporate_relevance = if(application_name_normalized = "lm studio", "Local model execution; review model provenance, resource use, listener exposure and optional cloud connections.", corporate_relevance), review_priority = if(application_name_normalized = "lm studio", "POLICY_DEPENDENT_UNASSIGNED", review_priority)
| alter detected_product = if(application_name_normalized = "gpt4all", "GPT4All", detected_product), product_id = if(application_name_normalized = "gpt4all", "gpt4all", product_id), tool_family = if(application_name_normalized = "gpt4all", "Local AI / LLM Runtimes", tool_family), tool_subcategory = if(application_name_normalized = "gpt4all", "local-model-runtime", tool_subcategory), expected_product_vendor = if(application_name_normalized = "gpt4all", "Nomic AI", expected_product_vendor), corporate_relevance = if(application_name_normalized = "gpt4all", "Local model execution; review model provenance, resource use, listener exposure and optional cloud connections.", corporate_relevance), review_priority = if(application_name_normalized = "gpt4all", "POLICY_DEPENDENT_UNASSIGNED", review_priority)
| alter detected_product = if(application_name_normalized = "llama.cpp", "llama.cpp", detected_product), product_id = if(application_name_normalized = "llama.cpp", "llama-cpp", product_id), tool_family = if(application_name_normalized = "llama.cpp", "Local AI / LLM Runtimes", tool_family), tool_subcategory = if(application_name_normalized = "llama.cpp", "inference-engine", tool_subcategory), expected_product_vendor = if(application_name_normalized = "llama.cpp", "ggml-org contributors", expected_product_vendor), corporate_relevance = if(application_name_normalized = "llama.cpp", "Local model execution; review model provenance, resource use, listener exposure and optional cloud connections.", corporate_relevance), review_priority = if(application_name_normalized = "llama.cpp", "POLICY_DEPENDENT_UNASSIGNED", review_priority)
| filter product_id != "UNMAPPED"
| fields endpoint_name, platform, application_name, version, application_name_normalized, detected_product, product_id, tool_family, tool_subcategory, expected_product_vendor, corporate_relevance, review_priority
| limit 1000
