config case_sensitive = false timeframe = 30d
| preset = host_inventory_applications
| filter application_name != null and application_name != ""
| fields endpoint_name, platform, application_name, version
| alter application_name_normalized = lowercase(application_name)
| filter application_name_normalized in ("1password", "bitwarden", "keepass password safe", "keepass password safe 2", "keepassxc")
| alter detected_product = "UNMAPPED", product_id = "UNMAPPED", tool_family = "UNMAPPED", tool_subcategory = "UNMAPPED", expected_product_vendor = "UNMAPPED", corporate_relevance = "UNMAPPED", review_priority = "UNMAPPED"
| alter detected_product = if(application_name_normalized = "1password", "1Password", detected_product), product_id = if(application_name_normalized = "1password", "1password", product_id), tool_family = if(application_name_normalized = "1password", "Password Managers", tool_family), tool_subcategory = if(application_name_normalized = "1password", "credential-vault", tool_subcategory), expected_product_vendor = if(application_name_normalized = "1password", "1Password", expected_product_vendor), corporate_relevance = if(application_name_normalized = "1password", "Credential storage; review vault ownership, recovery, sharing, MFA and enterprise enrollment.", corporate_relevance), review_priority = if(application_name_normalized = "1password", "POLICY_DEPENDENT_UNASSIGNED", review_priority)
| alter detected_product = if(application_name_normalized = "bitwarden", "Bitwarden", detected_product), product_id = if(application_name_normalized = "bitwarden", "bitwarden", product_id), tool_family = if(application_name_normalized = "bitwarden", "Password Managers", tool_family), tool_subcategory = if(application_name_normalized = "bitwarden", "credential-vault", tool_subcategory), expected_product_vendor = if(application_name_normalized = "bitwarden", "Bitwarden", expected_product_vendor), corporate_relevance = if(application_name_normalized = "bitwarden", "Credential storage; review vault ownership, recovery, sharing, MFA and enterprise enrollment.", corporate_relevance), review_priority = if(application_name_normalized = "bitwarden", "POLICY_DEPENDENT_UNASSIGNED", review_priority)
| alter detected_product = if(application_name_normalized in ("keepass password safe", "keepass password safe 2"), "KeePass Password Safe", detected_product), product_id = if(application_name_normalized in ("keepass password safe", "keepass password safe 2"), "keepass", product_id), tool_family = if(application_name_normalized in ("keepass password safe", "keepass password safe 2"), "Password Managers", tool_family), tool_subcategory = if(application_name_normalized in ("keepass password safe", "keepass password safe 2"), "local-credential-vault", tool_subcategory), expected_product_vendor = if(application_name_normalized in ("keepass password safe", "keepass password safe 2"), "Dominik Reichl / KeePass project", expected_product_vendor), corporate_relevance = if(application_name_normalized in ("keepass password safe", "keepass password safe 2"), "Credential storage; review vault ownership, recovery, sharing, MFA and enterprise enrollment.", corporate_relevance), review_priority = if(application_name_normalized in ("keepass password safe", "keepass password safe 2"), "POLICY_DEPENDENT_UNASSIGNED", review_priority)
| alter detected_product = if(application_name_normalized = "keepassxc", "KeePassXC", detected_product), product_id = if(application_name_normalized = "keepassxc", "keepassxc", product_id), tool_family = if(application_name_normalized = "keepassxc", "Password Managers", tool_family), tool_subcategory = if(application_name_normalized = "keepassxc", "local-credential-vault", tool_subcategory), expected_product_vendor = if(application_name_normalized = "keepassxc", "KeePassXC Team", expected_product_vendor), corporate_relevance = if(application_name_normalized = "keepassxc", "Credential storage; review vault ownership, recovery, sharing, MFA and enterprise enrollment.", corporate_relevance), review_priority = if(application_name_normalized = "keepassxc", "POLICY_DEPENDENT_UNASSIGNED", review_priority)
| filter product_id != "UNMAPPED"
| fields endpoint_name, platform, application_name, version, application_name_normalized, detected_product, product_id, tool_family, tool_subcategory, expected_product_vendor, corporate_relevance, review_priority
| limit 1000
